// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAgents = `-- name: CountAgents :one
SELECT COUNT(*) FROM agents_view
`

func (q *Queries) CountAgents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAgents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAgent = `-- name: InsertAgent :one
INSERT INTO agents (name, description, is_active, webhook_uri)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, description, is_active, webhook_uri, created_at, updated_at
`

type InsertAgentParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsActive    bool    `json:"is_active"`
	WebhookUri  string  `json:"webhook_uri"`
}

type InsertAgentRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsActive    bool      `json:"is_active"`
	WebhookUri  string    `json:"webhook_uri"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) InsertAgent(ctx context.Context, arg InsertAgentParams) (InsertAgentRow, error) {
	row := q.db.QueryRow(ctx, insertAgent,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.WebhookUri,
	)
	var i InsertAgentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.WebhookUri,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectAgentById = `-- name: SelectAgentById :one
SELECT
    av.id, av.name, av.description, av.is_active, av.webhook_uri, av.created_at, av.updated_at,
    (
        SELECT COUNT(*) FROM agent_knowledges_view akv
        WHERE akv.agent_id = av.id
    ) AS knowledges_count,
    (
        SELECT COUNT(*) FROM mcps_view mv
        WHERE mv.agent_id = av.id
    ) AS mcps_count
FROM agents_view av
WHERE av.id = $1
LIMIT 1
`

type SelectAgentByIdRow struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Description     *string   `json:"description"`
	IsActive        bool      `json:"is_active"`
	WebhookUri      string    `json:"webhook_uri"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	KnowledgesCount int64     `json:"knowledges_count"`
	McpsCount       int64     `json:"mcps_count"`
}

func (q *Queries) SelectAgentById(ctx context.Context, id uuid.UUID) (SelectAgentByIdRow, error) {
	row := q.db.QueryRow(ctx, selectAgentById, id)
	var i SelectAgentByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.WebhookUri,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KnowledgesCount,
		&i.McpsCount,
	)
	return i, err
}

const selectAgents = `-- name: SelectAgents :many
SELECT
    av.id, av.name, av.description, av.is_active, av.webhook_uri, av.created_at, av.updated_at,
    COALESCE(ak.knowledges_count, 0) AS knowledges_count,
    COALESCE(m.mcps_count, 0) AS mcps_count
FROM agents_view av
LEFT JOIN (
    SELECT
        agent_id,
        COUNT(*) AS knowledges_count
    FROM agent_knowledges_view
    GROUP BY agent_id
) ak ON ak.agent_id = av.id
LEFT JOIN (
    SELECT
        agent_id,
        COUNT(*) AS mcps_count
    FROM mcps_view
    GROUP BY agent_id
) m ON m.agent_id = av.id
WHERE (
    $1::bool IS NULL
    OR av.is_active = $1::bool
)
ORDER BY
    CASE
        WHEN $2::text = 'is_active_asc' THEN av.is_active
    END DESC,
    CASE
        WHEN $2::text = 'is_active_desc' THEN av.is_active
    END ASC,
    CASE WHEN $2::text = 'name_asc' THEN av.name END ASC,
    CASE WHEN $2::text = 'name_desc' THEN av.name END DESC,
    CASE WHEN $2::text = 'created_asc' THEN av.created_at END ASC,
    CASE
        WHEN $2::text = 'created_desc' THEN av.created_at
    END DESC,
    av.created_at DESC
LIMIT $4 OFFSET $3
`

type SelectAgentsParams struct {
	IsActive *bool   `json:"is_active"`
	Sort     *string `json:"sort"`
	Offset   int32   `json:"offset"`
	Limit    int32   `json:"limit"`
}

type SelectAgentsRow struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Description     *string   `json:"description"`
	IsActive        bool      `json:"is_active"`
	WebhookUri      string    `json:"webhook_uri"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	KnowledgesCount int64     `json:"knowledges_count"`
	McpsCount       int64     `json:"mcps_count"`
}

func (q *Queries) SelectAgents(ctx context.Context, arg SelectAgentsParams) ([]SelectAgentsRow, error) {
	rows, err := q.db.Query(ctx, selectAgents,
		arg.IsActive,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectAgentsRow{}
	for rows.Next() {
		var i SelectAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.WebhookUri,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KnowledgesCount,
			&i.McpsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAgent = `-- name: SoftDeleteAgent :execrows
UPDATE agents
SET deleted_at = now()
WHERE
    deleted_at IS NULL
    AND id = $1
`

func (q *Queries) SoftDeleteAgent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAgent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET
    name = $1,
    description = $2,
    is_active = $3,
    webhook_uri = $4,
    updated_at = NOW()
WHERE
    deleted_at IS NULL
    AND id = $5
RETURNING id, name, description, is_active, webhook_uri, created_at, updated_at
`

type UpdateAgentParams struct {
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsActive    bool      `json:"is_active"`
	WebhookUri  string    `json:"webhook_uri"`
	ID          uuid.UUID `json:"id"`
}

type UpdateAgentRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsActive    bool      `json:"is_active"`
	WebhookUri  string    `json:"webhook_uri"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (UpdateAgentRow, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.WebhookUri,
		arg.ID,
	)
	var i UpdateAgentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.WebhookUri,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
