// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agentKnowledges.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAgentKnowledgesByAgentId = `-- name: CountAgentKnowledgesByAgentId :one
SELECT COUNT(*)
FROM agent_knowledges_view akv
JOIN knowledges_view kv
    ON akv.knowledge_id = kv.id
WHERE akv.agent_id = $1
`

func (q *Queries) CountAgentKnowledgesByAgentId(ctx context.Context, agentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentKnowledgesByAgentId, agentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAgentKnowledge = `-- name: InsertAgentKnowledge :one
INSERT INTO agent_knowledges (agent_id, knowledge_id)
VALUES (
    $1,
    $2
)
RETURNING
    id, agent_id, knowledge_id, is_active_prod, is_active_dev, status, created_at, updated_at
`

type InsertAgentKnowledgeParams struct {
	AgentID     uuid.UUID `json:"agent_id"`
	KnowledgeID uuid.UUID `json:"knowledge_id"`
}

type InsertAgentKnowledgeRow struct {
	ID           uuid.UUID `json:"id"`
	AgentID      uuid.UUID `json:"agent_id"`
	KnowledgeID  uuid.UUID `json:"knowledge_id"`
	IsActiveProd bool      `json:"is_active_prod"`
	IsActiveDev  bool      `json:"is_active_dev"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) InsertAgentKnowledge(ctx context.Context, arg InsertAgentKnowledgeParams) (InsertAgentKnowledgeRow, error) {
	row := q.db.QueryRow(ctx, insertAgentKnowledge, arg.AgentID, arg.KnowledgeID)
	var i InsertAgentKnowledgeRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.KnowledgeID,
		&i.IsActiveProd,
		&i.IsActiveDev,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectAgentKnowledgesByAgentId = `-- name: SelectAgentKnowledgesByAgentId :many
SELECT
    akv.id, akv.agent_id, akv.knowledge_id, akv.is_active_prod, akv.is_active_dev, akv.created_at, akv.updated_at, akv.status,
    kv.id, kv.name, kv.description, kv.source_type, kv.source_uri, kv.created_at, kv.updated_at
FROM agent_knowledges_view akv
JOIN knowledges_view kv
    ON akv.knowledge_id = kv.id
WHERE akv.agent_id = $1
ORDER BY
    CASE
        WHEN $2::text = 'created_asc' THEN akv.created_at
    END ASC,
    CASE
        WHEN $2::text = 'created_desc' THEN akv.created_at
    END DESC,
    akv.created_at DESC
LIMIT $4 OFFSET $3
`

type SelectAgentKnowledgesByAgentIdParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Sort    *string   `json:"sort"`
	Offset  int32     `json:"offset"`
	Limit   int32     `json:"limit"`
}

type SelectAgentKnowledgesByAgentIdRow struct {
	ID             uuid.UUID      `json:"id"`
	AgentID        uuid.UUID      `json:"agent_id"`
	KnowledgeID    uuid.UUID      `json:"knowledge_id"`
	IsActiveProd   bool           `json:"is_active_prod"`
	IsActiveDev    bool           `json:"is_active_dev"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	Status         string         `json:"status"`
	KnowledgesView KnowledgesView `json:"knowledges_view"`
}

func (q *Queries) SelectAgentKnowledgesByAgentId(ctx context.Context, arg SelectAgentKnowledgesByAgentIdParams) ([]SelectAgentKnowledgesByAgentIdRow, error) {
	rows, err := q.db.Query(ctx, selectAgentKnowledgesByAgentId,
		arg.AgentID,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectAgentKnowledgesByAgentIdRow{}
	for rows.Next() {
		var i SelectAgentKnowledgesByAgentIdRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.KnowledgeID,
			&i.IsActiveProd,
			&i.IsActiveDev,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.KnowledgesView.ID,
			&i.KnowledgesView.Name,
			&i.KnowledgesView.Description,
			&i.KnowledgesView.SourceType,
			&i.KnowledgesView.SourceUri,
			&i.KnowledgesView.CreatedAt,
			&i.KnowledgesView.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAgentKnowledge = `-- name: SoftDeleteAgentKnowledge :execrows
UPDATE agent_knowledges
SET deleted_at = NOW()
WHERE
    deleted_at IS NULL
    AND id = $1
`

func (q *Queries) SoftDeleteAgentKnowledge(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAgentKnowledge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteAgentKnowledgeByPair = `-- name: SoftDeleteAgentKnowledgeByPair :one
UPDATE agent_knowledges
SET deleted_at = NOW()
WHERE
    deleted_at IS NULL
    AND agent_id = $1
    AND knowledge_id = $2
RETURNING id
`

type SoftDeleteAgentKnowledgeByPairParams struct {
	AgentID     uuid.UUID `json:"agent_id"`
	KnowledgeID uuid.UUID `json:"knowledge_id"`
}

func (q *Queries) SoftDeleteAgentKnowledgeByPair(ctx context.Context, arg SoftDeleteAgentKnowledgeByPairParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteAgentKnowledgeByPair, arg.AgentID, arg.KnowledgeID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateAgentKnowledge = `-- name: UpdateAgentKnowledge :one
UPDATE agent_knowledges
SET
    is_active_prod = $1,
    is_active_dev = $2,
    updated_at = NOW()
WHERE
    deleted_at IS NULL
    AND id = $3
RETURNING
    id, agent_id, knowledge_id, is_active_prod, is_active_dev, status, created_at, updated_at
`

type UpdateAgentKnowledgeParams struct {
	IsActiveProd bool      `json:"is_active_prod"`
	IsActiveDev  bool      `json:"is_active_dev"`
	ID           uuid.UUID `json:"id"`
}

type UpdateAgentKnowledgeRow struct {
	ID           uuid.UUID `json:"id"`
	AgentID      uuid.UUID `json:"agent_id"`
	KnowledgeID  uuid.UUID `json:"knowledge_id"`
	IsActiveProd bool      `json:"is_active_prod"`
	IsActiveDev  bool      `json:"is_active_dev"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) UpdateAgentKnowledge(ctx context.Context, arg UpdateAgentKnowledgeParams) (UpdateAgentKnowledgeRow, error) {
	row := q.db.QueryRow(ctx, updateAgentKnowledge, arg.IsActiveProd, arg.IsActiveDev, arg.ID)
	var i UpdateAgentKnowledgeRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.KnowledgeID,
		&i.IsActiveProd,
		&i.IsActiveDev,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentKnowledgeStatus = `-- name: UpdateAgentKnowledgeStatus :execrows
UPDATE agent_knowledges
SET
    status = $1,
    updated_at = NOW()
WHERE
    deleted_at IS NULL
    AND id = $2
`

type UpdateAgentKnowledgeStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAgentKnowledgeStatus(ctx context.Context, arg UpdateAgentKnowledgeStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAgentKnowledgeStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
