// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agentMcps.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertAgentMcp = `-- name: InsertAgentMcp :one
INSERT INTO agent_mcps (agent_id, mcp_id)
VALUES (
    $1,
    $2
)
RETURNING
    id, agent_id, mcp_id, created_at, updated_at
`

type InsertAgentMcpParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	McpID   uuid.UUID `json:"mcp_id"`
}

type InsertAgentMcpRow struct {
	ID        uuid.UUID `json:"id"`
	AgentID   uuid.UUID `json:"agent_id"`
	McpID     uuid.UUID `json:"mcp_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) InsertAgentMcp(ctx context.Context, arg InsertAgentMcpParams) (InsertAgentMcpRow, error) {
	row := q.db.QueryRow(ctx, insertAgentMcp, arg.AgentID, arg.McpID)
	var i InsertAgentMcpRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.McpID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteAgentMcp = `-- name: SoftDeleteAgentMcp :execrows
UPDATE agent_mcps
SET deleted_at = NOW()
WHERE
    deleted_at IS NULL
    AND agent_id = $1
    AND mcp_id = $2
`

type SoftDeleteAgentMcpParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	McpID   uuid.UUID `json:"mcp_id"`
}

func (q *Queries) SoftDeleteAgentMcp(ctx context.Context, arg SoftDeleteAgentMcpParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAgentMcp, arg.AgentID, arg.McpID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
