// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agentKnowledges.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteAgentKnowledge = `-- name: DeleteAgentKnowledge :execrows
DELETE FROM agent_knowledges
WHERE
    deleted_at IS NULL
    AND id = $1
`

func (q *Queries) DeleteAgentKnowledge(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentKnowledge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAgentKnowledge = `-- name: InsertAgentKnowledge :one
INSERT INTO agent_knowledges (agent_id, knowledge_id)
VALUES (
    $1,
    $2
)
RETURNING id, is_active_prod, is_active_dev, agent_id, knowledge_id, created_at, updated_at, deleted_at
`

type InsertAgentKnowledgeParams struct {
	AgentID     uuid.UUID `json:"agent_id"`
	KnowledgeID uuid.UUID `json:"knowledge_id"`
}

func (q *Queries) InsertAgentKnowledge(ctx context.Context, arg InsertAgentKnowledgeParams) (AgentKnowledge, error) {
	row := q.db.QueryRow(ctx, insertAgentKnowledge, arg.AgentID, arg.KnowledgeID)
	var i AgentKnowledge
	err := row.Scan(
		&i.ID,
		&i.IsActiveProd,
		&i.IsActiveDev,
		&i.AgentID,
		&i.KnowledgeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectAgentKnowledgesByAgentId = `-- name: SelectAgentKnowledgesByAgentId :many
SELECT
    ak.id, ak.is_active_prod, ak.is_active_dev, ak.agent_id, ak.knowledge_id, ak.created_at, ak.updated_at, ak.deleted_at,
    k.id, k.name, k.description, k.source_type, k.source_uri, k.created_at, k.updated_at, k.deleted_at
FROM agent_knowledges ak
JOIN knowledges k
    ON ak.knowledge_id = k.id
WHERE
    ak.deleted_at IS NULL
    AND ak.agent_id = $1
LIMIT
    coalesce($3, 10)
    OFFSET coalesce($2, 0)
`

type SelectAgentKnowledgesByAgentIdParams struct {
	AgentID uuid.UUID   `json:"agent_id"`
	Offset  interface{} `json:"offset"`
	Limit   interface{} `json:"limit"`
}

type SelectAgentKnowledgesByAgentIdRow struct {
	ID           uuid.UUID  `json:"id"`
	IsActiveProd bool       `json:"is_active_prod"`
	IsActiveDev  bool       `json:"is_active_dev"`
	AgentID      uuid.UUID  `json:"agent_id"`
	KnowledgeID  uuid.UUID  `json:"knowledge_id"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
	Knowledge    Knowledge  `json:"knowledge"`
}

func (q *Queries) SelectAgentKnowledgesByAgentId(ctx context.Context, arg SelectAgentKnowledgesByAgentIdParams) ([]SelectAgentKnowledgesByAgentIdRow, error) {
	rows, err := q.db.Query(ctx, selectAgentKnowledgesByAgentId, arg.AgentID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectAgentKnowledgesByAgentIdRow{}
	for rows.Next() {
		var i SelectAgentKnowledgesByAgentIdRow
		if err := rows.Scan(
			&i.ID,
			&i.IsActiveProd,
			&i.IsActiveDev,
			&i.AgentID,
			&i.KnowledgeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Knowledge.ID,
			&i.Knowledge.Name,
			&i.Knowledge.Description,
			&i.Knowledge.SourceType,
			&i.Knowledge.SourceUri,
			&i.Knowledge.CreatedAt,
			&i.Knowledge.UpdatedAt,
			&i.Knowledge.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentKnowledge = `-- name: UpdateAgentKnowledge :one
UPDATE agent_knowledges
SET
    is_active_prod = $1,
    is_active_dev = $2,
    updated_at = now()
WHERE
    deleted_at IS NULL
    AND id = $3
RETURNING id, is_active_prod, is_active_dev, agent_id, knowledge_id, created_at, updated_at, deleted_at
`

type UpdateAgentKnowledgeParams struct {
	IsActiveProd bool      `json:"is_active_prod"`
	IsActiveDev  bool      `json:"is_active_dev"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAgentKnowledge(ctx context.Context, arg UpdateAgentKnowledgeParams) (AgentKnowledge, error) {
	row := q.db.QueryRow(ctx, updateAgentKnowledge, arg.IsActiveProd, arg.IsActiveDev, arg.ID)
	var i AgentKnowledge
	err := row.Scan(
		&i.ID,
		&i.IsActiveProd,
		&i.IsActiveDev,
		&i.AgentID,
		&i.KnowledgeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
