// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteAgent = `-- name: DeleteAgent :execrows
DELETE FROM agents
WHERE
    deleted_at IS NULL
    AND id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAgent = `-- name: InsertAgent :one
INSERT INTO agents (name, description, is_active, webhook_uri)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, description, is_active, webhook_uri, created_at, updated_at, deleted_at
`

type InsertAgentParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsActive    bool    `json:"is_active"`
	WebhookUri  string  `json:"webhook_uri"`
}

func (q *Queries) InsertAgent(ctx context.Context, arg InsertAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, insertAgent,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.WebhookUri,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.WebhookUri,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectAgentById = `-- name: SelectAgentById :one
SELECT id, name, description, is_active, webhook_uri, created_at, updated_at, deleted_at FROM agents
WHERE
    deleted_at IS NULL
    AND id = $1
LIMIT 1
`

func (q *Queries) SelectAgentById(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, selectAgentById, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.WebhookUri,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectAgents = `-- name: SelectAgents :many
SELECT id, name, description, is_active, webhook_uri, created_at, updated_at, deleted_at FROM agents
WHERE
    deleted_at IS NULL
    AND (
        $1::bool IS NULL
        OR is_active = $1::bool
    )
ORDER BY
    CASE WHEN $2::text = 'is_active_asc' THEN is_active END ASC,
    CASE WHEN $2::text = 'is_active_desc' THEN is_active END ASC,
    CASE WHEN $2::text = 'name_asc' THEN name END ASC,
    CASE WHEN $2::text = 'name_desc' THEN name END DESC,
    CASE WHEN $2::text = 'created_asc' THEN created_at END ASC,
    CASE WHEN $2::text = 'created_desc' THEN created_at END DESC,
    created_at DESC
LIMIT $4 OFFSET $3
`

type SelectAgentsParams struct {
	IsActive *bool   `json:"is_active"`
	Sort     *string `json:"sort"`
	Offset   int32   `json:"offset"`
	Limit    int32   `json:"limit"`
}

func (q *Queries) SelectAgents(ctx context.Context, arg SelectAgentsParams) ([]Agent, error) {
	rows, err := q.db.Query(ctx, selectAgents,
		arg.IsActive,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.WebhookUri,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET
    name = $1,
    description = $2,
    is_active = $3,
    webhook_uri = $4,
    updated_at = now()
WHERE
    deleted_at IS NULL
    AND id = $5
RETURNING id, name, description, is_active, webhook_uri, created_at, updated_at, deleted_at
`

type UpdateAgentParams struct {
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsActive    bool      `json:"is_active"`
	WebhookUri  string    `json:"webhook_uri"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.WebhookUri,
		arg.ID,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.WebhookUri,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
