// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apiKeys.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countApiKeys = `-- name: CountApiKeys :one
SELECT COUNT(*) FROM api_keys_view
`

func (q *Queries) CountApiKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countApiKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertApiKey = `-- name: InsertApiKey :one
INSERT INTO api_keys (name, token)
VALUES (
    $1,
    $2
)
RETURNING id, name, token, created_at
`

type InsertApiKeyParams struct {
	Name  string `json:"name"`
	Token string `json:"token"`
}

type InsertApiKeyRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertApiKey(ctx context.Context, arg InsertApiKeyParams) (InsertApiKeyRow, error) {
	row := q.db.QueryRow(ctx, insertApiKey, arg.Name, arg.Token)
	var i InsertApiKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Token,
		&i.CreatedAt,
	)
	return i, err
}

const revokeApiKey = `-- name: RevokeApiKey :execrows
UPDATE api_keys
SET revoked_at = NOW()
WHERE
    revoked_at IS NULL
    AND id = $1
`

func (q *Queries) RevokeApiKey(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeApiKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const selectApiKeyByToken = `-- name: SelectApiKeyByToken :one
SELECT id, name, token, created_at FROM api_keys_view
WHERE token = $1
`

func (q *Queries) SelectApiKeyByToken(ctx context.Context, token string) (ApiKeysView, error) {
	row := q.db.QueryRow(ctx, selectApiKeyByToken, token)
	var i ApiKeysView
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Token,
		&i.CreatedAt,
	)
	return i, err
}

const selectApiKeys = `-- name: SelectApiKeys :many
SELECT id, name, token, created_at FROM api_keys_view
ORDER BY
    CASE WHEN $1::text = 'name_asc' THEN name END ASC,
    CASE WHEN $1::text = 'name_desc' THEN name END DESC,
    CASE WHEN $1::text = 'created_asc' THEN created_at END ASC,
    CASE WHEN $1::text = 'created_desc' THEN created_at END DESC,
    created_at DESC
LIMIT $3 OFFSET $2
`

type SelectApiKeysParams struct {
	Sort   *string `json:"sort"`
	Offset int32   `json:"offset"`
	Limit  int32   `json:"limit"`
}

func (q *Queries) SelectApiKeys(ctx context.Context, arg SelectApiKeysParams) ([]ApiKeysView, error) {
	rows, err := q.db.Query(ctx, selectApiKeys, arg.Sort, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKeysView{}
	for rows.Next() {
		var i ApiKeysView
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Token,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
