// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auths.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertUserRegister = `-- name: InsertUserRegister :one
INSERT INTO users (name, username, email, hashed_password)
VALUES (
    $1,
    $1,
    $2,
    $3
)
RETURNING id, name, username, email, role, created_at, updated_at
`

type InsertUserRegisterParams struct {
	Username       string `json:"username"`
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
}

type InsertUserRegisterRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Role      UserRole  `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) InsertUserRegister(ctx context.Context, arg InsertUserRegisterParams) (InsertUserRegisterRow, error) {
	row := q.db.QueryRow(ctx, insertUserRegister, arg.Username, arg.Email, arg.HashedPassword)
	var i InsertUserRegisterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectUserByLoginIdWithPassword = `-- name: SelectUserByLoginIdWithPassword :one
SELECT
    id,
    name,
    username,
    email,
    role,
    hashed_password,
    created_at,
    updated_at
FROM users
WHERE
    deleted_at IS NULL
    AND (
        username = $1
        OR email = $1
    )
LIMIT 1
`

type SelectUserByLoginIdWithPasswordRow struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Username       string    `json:"username"`
	Email          string    `json:"email"`
	Role           UserRole  `json:"role"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) SelectUserByLoginIdWithPassword(ctx context.Context, loginID string) (SelectUserByLoginIdWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, selectUserByLoginIdWithPassword, loginID)
	var i SelectUserByLoginIdWithPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
