// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auths.sql

package db

import (
	"context"
)

const insertUserRegister = `-- name: InsertUserRegister :one
INSERT INTO users (name, username, email, hashed_password)
VALUES (
    $1,
    $1,
    $2,
    $3
)
RETURNING id, name, username, email, role, hashed_password, created_at, updated_at, deleted_at
`

type InsertUserRegisterParams struct {
	Username       string `json:"username"`
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) InsertUserRegister(ctx context.Context, arg InsertUserRegisterParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUserRegister, arg.Username, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectUserByLoginId = `-- name: SelectUserByLoginId :one
SELECT id, name, username, email, role, hashed_password, created_at, updated_at, deleted_at FROM users
WHERE
    deleted_at IS null
    AND (
        username = $1
        OR email = $1
    )
LIMIT 1
`

func (q *Queries) SelectUserByLoginId(ctx context.Context, loginID string) (User, error) {
	row := q.db.QueryRow(ctx, selectUserByLoginId, loginID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
