// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const closeConversation = `-- name: CloseConversation :exec
UPDATE conversations
SET
    is_active = false,
    ended_at = $1::TIMESTAMPTZ,
    end_reason = upper($2::TEXT)::CONVERSATION_END_REASON,
    resolution_ms = $3::BIGINT
WHERE id = $4 AND is_active = true
`

type CloseConversationParams struct {
	EndedAt      time.Time `json:"ended_at"`
	EndReason    string    `json:"end_reason"`
	ResolutionMs int64     `json:"resolution_ms"`
	ID           uuid.UUID `json:"id"`
}

// Marks a conversation ended. end_reason arrives lowercase on the wire
// (e.g. "timed_out"); upper() maps it onto the CONVERSATION_END_REASON enum.
// Guarded by is_active so a replayed/duplicate end event is a no-op.
func (q *Queries) CloseConversation(ctx context.Context, arg CloseConversationParams) error {
	_, err := q.db.Exec(ctx, closeConversation,
		arg.EndedAt,
		arg.EndReason,
		arg.ResolutionMs,
		arg.ID,
	)
	return err
}

const countConversations = `-- name: CountConversations :one
SELECT count(*) FROM conversations_view
`

func (q *Queries) CountConversations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countConversations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const deleteMessagesByConversation = `-- name: DeleteMessagesByConversation :exec
DELETE FROM messages WHERE conversation_id = $1
`

func (q *Queries) DeleteMessagesByConversation(ctx context.Context, conversationID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessagesByConversation, conversationID)
	return err
}

const selectConversationById = `-- name: SelectConversationById :one
SELECT
    c.id,
    c.agent_id,
    a.name AS agent_name,
    c.started_at,
    c.ended_at,
    c.is_active
FROM conversations_view AS c
INNER JOIN agents AS a ON c.agent_id = a.id
WHERE c.id = $1
`

type SelectConversationByIdRow struct {
	ID        uuid.UUID  `json:"id"`
	AgentID   uuid.UUID  `json:"agent_id"`
	AgentName string     `json:"agent_name"`
	StartedAt time.Time  `json:"started_at"`
	EndedAt   *time.Time `json:"ended_at"`
	IsActive  bool       `json:"is_active"`
}

func (q *Queries) SelectConversationById(ctx context.Context, id uuid.UUID) (SelectConversationByIdRow, error) {
	row := q.db.QueryRow(ctx, selectConversationById, id)
	var i SelectConversationByIdRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.AgentName,
		&i.StartedAt,
		&i.EndedAt,
		&i.IsActive,
	)
	return i, err
}

const selectConversations = `-- name: SelectConversations :many
SELECT
    c.id,
    c.agent_id,
    a.name AS agent_name,
    c.started_at,
    c.ended_at,
    c.is_active,
    lm.content AS last_message,
    lm.created_at AS last_message_at,
    (
        SELECT count(*) FROM messages AS m
        WHERE m.conversation_id = c.id
    ) AS message_count
FROM conversations_view AS c
INNER JOIN agents AS a ON c.agent_id = a.id
LEFT JOIN LATERAL (
    SELECT
        m.content,
        m.created_at
    FROM messages AS m
    WHERE m.conversation_id = c.id
    ORDER BY m.created_at DESC
    LIMIT 1
) AS lm ON true
ORDER BY coalesce(lm.created_at, c.started_at) DESC
LIMIT $2 OFFSET $1
`

type SelectConversationsParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

type SelectConversationsRow struct {
	ID            uuid.UUID  `json:"id"`
	AgentID       uuid.UUID  `json:"agent_id"`
	AgentName     string     `json:"agent_name"`
	StartedAt     time.Time  `json:"started_at"`
	EndedAt       *time.Time `json:"ended_at"`
	IsActive      bool       `json:"is_active"`
	LastMessage   *string    `json:"last_message"`
	LastMessageAt time.Time  `json:"last_message_at"`
	MessageCount  int64      `json:"message_count"`
}

func (q *Queries) SelectConversations(ctx context.Context, arg SelectConversationsParams) ([]SelectConversationsRow, error) {
	rows, err := q.db.Query(ctx, selectConversations, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectConversationsRow{}
	for rows.Next() {
		var i SelectConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.AgentName,
			&i.StartedAt,
			&i.EndedAt,
			&i.IsActive,
			&i.LastMessage,
			&i.LastMessageAt,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConversation = `-- name: UpsertConversation :exec
INSERT INTO conversations (id, agent_id)
VALUES ($1, $2)
ON CONFLICT (id) DO NOTHING
`

type UpsertConversationParams struct {
	ID      uuid.UUID `json:"id"`
	AgentID uuid.UUID `json:"agent_id"`
}

func (q *Queries) UpsertConversation(ctx context.Context, arg UpsertConversationParams) error {
	_, err := q.db.Exec(ctx, upsertConversation, arg.ID, arg.AgentID)
	return err
}
