// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboards.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteDashboardImport = `-- name: DeleteDashboardImport :execrows
DELETE FROM dashboard_imports
WHERE dashboard_id = $1 AND user_id = $2
`

type DeleteDashboardImportParams struct {
	DashboardID uuid.UUID `json:"dashboard_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDashboardImport(ctx context.Context, arg DeleteDashboardImportParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDashboardImport, arg.DashboardID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertDashboard = `-- name: InsertDashboard :one
INSERT INTO dashboards (owner_id, name, description, config)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, owner_id, name, description, config, visibility, published_at, published_by, created_at, updated_at
`

type InsertDashboardParams struct {
	OwnerID     uuid.UUID       `json:"owner_id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Config      json.RawMessage `json:"config"`
}

type InsertDashboardRow struct {
	ID          uuid.UUID       `json:"id"`
	OwnerID     uuid.UUID       `json:"owner_id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Config      json.RawMessage `json:"config"`
	Visibility  string          `json:"visibility"`
	PublishedAt *time.Time      `json:"published_at"`
	PublishedBy *uuid.UUID      `json:"published_by"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) InsertDashboard(ctx context.Context, arg InsertDashboardParams) (InsertDashboardRow, error) {
	row := q.db.QueryRow(ctx, insertDashboard,
		arg.OwnerID,
		arg.Name,
		arg.Description,
		arg.Config,
	)
	var i InsertDashboardRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.Visibility,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDashboardImport = `-- name: InsertDashboardImport :execrows
INSERT INTO dashboard_imports (dashboard_id, user_id)
VALUES ($1, $2)
ON CONFLICT (dashboard_id, user_id) DO NOTHING
`

type InsertDashboardImportParams struct {
	DashboardID uuid.UUID `json:"dashboard_id"`
	UserID      uuid.UUID `json:"user_id"`
}

// Idempotent import: ON CONFLICT means re-importing is a no-op.
func (q *Queries) InsertDashboardImport(ctx context.Context, arg InsertDashboardImportParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDashboardImport, arg.DashboardID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const publishDashboard = `-- name: PublishDashboard :one
UPDATE dashboards
SET
    visibility = 'published',
    published_at = now(),
    published_by = $1,
    updated_at = now()
WHERE
    deleted_at IS NULL
    AND id = $2
RETURNING id, owner_id, name, description, config, visibility, published_at, published_by, created_at, updated_at
`

type PublishDashboardParams struct {
	PublishedBy *uuid.UUID `json:"published_by"`
	ID          uuid.UUID  `json:"id"`
}

type PublishDashboardRow struct {
	ID          uuid.UUID       `json:"id"`
	OwnerID     uuid.UUID       `json:"owner_id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Config      json.RawMessage `json:"config"`
	Visibility  string          `json:"visibility"`
	PublishedAt *time.Time      `json:"published_at"`
	PublishedBy *uuid.UUID      `json:"published_by"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

// Admin-gated at the handler; records who published and when.
func (q *Queries) PublishDashboard(ctx context.Context, arg PublishDashboardParams) (PublishDashboardRow, error) {
	row := q.db.QueryRow(ctx, publishDashboard, arg.PublishedBy, arg.ID)
	var i PublishDashboardRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.Visibility,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectDashboardById = `-- name: SelectDashboardById :one
SELECT id, owner_id, name, description, config, visibility, published_at, published_by, created_at, updated_at FROM dashboards_view
WHERE id = $1
LIMIT 1
`

func (q *Queries) SelectDashboardById(ctx context.Context, id uuid.UUID) (DashboardsView, error) {
	row := q.db.QueryRow(ctx, selectDashboardById, id)
	var i DashboardsView
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.Visibility,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectDashboardImport = `-- name: SelectDashboardImport :one
SELECT id, dashboard_id, user_id, created_at FROM dashboard_imports
WHERE dashboard_id = $1 AND user_id = $2
LIMIT 1
`

type SelectDashboardImportParams struct {
	DashboardID uuid.UUID `json:"dashboard_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) SelectDashboardImport(ctx context.Context, arg SelectDashboardImportParams) (DashboardImport, error) {
	row := q.db.QueryRow(ctx, selectDashboardImport, arg.DashboardID, arg.UserID)
	var i DashboardImport
	err := row.Scan(
		&i.ID,
		&i.DashboardID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const selectMyDashboards = `-- name: SelectMyDashboards :many
SELECT
    d.id, d.owner_id, d.name, d.description, d.config, d.visibility, d.published_at, d.published_by, d.created_at, d.updated_at,
    (d.owner_id = $1)::bool AS is_owner,
    (di.id IS NOT NULL)::bool AS imported,
    u.name AS owner_name
FROM dashboards_view d
LEFT JOIN dashboard_imports di
    ON di.dashboard_id = d.id AND di.user_id = $1
JOIN users u ON u.id = d.owner_id
WHERE
    d.owner_id = $1
    OR di.id IS NOT NULL
ORDER BY is_owner DESC, d.created_at DESC
`

type SelectMyDashboardsRow struct {
	ID          uuid.UUID       `json:"id"`
	OwnerID     uuid.UUID       `json:"owner_id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Config      json.RawMessage `json:"config"`
	Visibility  string          `json:"visibility"`
	PublishedAt *time.Time      `json:"published_at"`
	PublishedBy *uuid.UUID      `json:"published_by"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	IsOwner     bool            `json:"is_owner"`
	Imported    bool            `json:"imported"`
	OwnerName   string          `json:"owner_name"`
}

// Everything the caller can see in their sidebar: dashboards they own PLUS
// published dashboards they've imported. `is_owner` distinguishes edit rights;
// `imported` flags the ones that came from someone else.
func (q *Queries) SelectMyDashboards(ctx context.Context, userID uuid.UUID) ([]SelectMyDashboardsRow, error) {
	rows, err := q.db.Query(ctx, selectMyDashboards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectMyDashboardsRow{}
	for rows.Next() {
		var i SelectMyDashboardsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.Visibility,
			&i.PublishedAt,
			&i.PublishedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsOwner,
			&i.Imported,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPublishedDashboards = `-- name: SelectPublishedDashboards :many
SELECT
    d.id, d.owner_id, d.name, d.description, d.config, d.visibility, d.published_at, d.published_by, d.created_at, d.updated_at,
    (d.owner_id = $1)::bool AS is_owner,
    (di.id IS NOT NULL)::bool AS imported,
    u.name AS owner_name
FROM dashboards_view d
LEFT JOIN dashboard_imports di
    ON di.dashboard_id = d.id AND di.user_id = $1
JOIN users u ON u.id = d.owner_id
WHERE d.visibility = 'published'
ORDER BY d.published_at DESC
`

type SelectPublishedDashboardsRow struct {
	ID          uuid.UUID       `json:"id"`
	OwnerID     uuid.UUID       `json:"owner_id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Config      json.RawMessage `json:"config"`
	Visibility  string          `json:"visibility"`
	PublishedAt *time.Time      `json:"published_at"`
	PublishedBy *uuid.UUID      `json:"published_by"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	IsOwner     bool            `json:"is_owner"`
	Imported    bool            `json:"imported"`
	OwnerName   string          `json:"owner_name"`
}

// The team catalog: all published dashboards, with a flag telling the caller
// which ones they've already imported and whether they own it.
func (q *Queries) SelectPublishedDashboards(ctx context.Context, userID uuid.UUID) ([]SelectPublishedDashboardsRow, error) {
	rows, err := q.db.Query(ctx, selectPublishedDashboards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectPublishedDashboardsRow{}
	for rows.Next() {
		var i SelectPublishedDashboardsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.Visibility,
			&i.PublishedAt,
			&i.PublishedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsOwner,
			&i.Imported,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDashboard = `-- name: SoftDeleteDashboard :execrows
UPDATE dashboards
SET deleted_at = now()
WHERE
    deleted_at IS NULL
    AND id = $1
    AND owner_id = $2
`

type SoftDeleteDashboardParams struct {
	ID      uuid.UUID `json:"id"`
	OwnerID uuid.UUID `json:"owner_id"`
}

// Owner-scoped delete.
func (q *Queries) SoftDeleteDashboard(ctx context.Context, arg SoftDeleteDashboardParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteDashboard, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unpublishDashboard = `-- name: UnpublishDashboard :one
UPDATE dashboards
SET
    visibility = 'private',
    published_at = NULL,
    published_by = NULL,
    updated_at = now()
WHERE
    deleted_at IS NULL
    AND id = $1
RETURNING id, owner_id, name, description, config, visibility, published_at, published_by, created_at, updated_at
`

type UnpublishDashboardRow struct {
	ID          uuid.UUID       `json:"id"`
	OwnerID     uuid.UUID       `json:"owner_id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Config      json.RawMessage `json:"config"`
	Visibility  string          `json:"visibility"`
	PublishedAt *time.Time      `json:"published_at"`
	PublishedBy *uuid.UUID      `json:"published_by"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) UnpublishDashboard(ctx context.Context, id uuid.UUID) (UnpublishDashboardRow, error) {
	row := q.db.QueryRow(ctx, unpublishDashboard, id)
	var i UnpublishDashboardRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.Visibility,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDashboard = `-- name: UpdateDashboard :one
UPDATE dashboards
SET
    name = $1,
    description = $2,
    config = $3,
    updated_at = now()
WHERE
    deleted_at IS NULL
    AND id = $4
    AND owner_id = $5
RETURNING id, owner_id, name, description, config, visibility, published_at, published_by, created_at, updated_at
`

type UpdateDashboardParams struct {
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Config      json.RawMessage `json:"config"`
	ID          uuid.UUID       `json:"id"`
	OwnerID     uuid.UUID       `json:"owner_id"`
}

type UpdateDashboardRow struct {
	ID          uuid.UUID       `json:"id"`
	OwnerID     uuid.UUID       `json:"owner_id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Config      json.RawMessage `json:"config"`
	Visibility  string          `json:"visibility"`
	PublishedAt *time.Time      `json:"published_at"`
	PublishedBy *uuid.UUID      `json:"published_by"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

// Owner-scoped: the WHERE clause enforces that only the owner's row is touched.
func (q *Queries) UpdateDashboard(ctx context.Context, arg UpdateDashboardParams) (UpdateDashboardRow, error) {
	row := q.db.QueryRow(ctx, updateDashboard,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.ID,
		arg.OwnerID,
	)
	var i UpdateDashboardRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.Visibility,
		&i.PublishedAt,
		&i.PublishedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
