// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dropdown.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const selectDropdownAgents = `-- name: SelectDropdownAgents :many
SELECT
    av.id,
    av.name,
    (akv.agent_id IS NOT NULL)::bool AS is_connected
FROM agents_view av
LEFT JOIN agent_knowledges_view akv
    ON
        akv.agent_id = av.id
        AND akv.knowledge_id = $1
WHERE (
    $2::text IS NULL
    OR $2::text = ''
    OR av.name ILIKE '%' || $2::text || '%'
)
ORDER BY av.name ASC
`

type SelectDropdownAgentsParams struct {
	KnowledgeID uuid.UUID `json:"knowledge_id"`
	Search      *string   `json:"search"`
}

type SelectDropdownAgentsRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	IsConnected bool      `json:"is_connected"`
}

func (q *Queries) SelectDropdownAgents(ctx context.Context, arg SelectDropdownAgentsParams) ([]SelectDropdownAgentsRow, error) {
	rows, err := q.db.Query(ctx, selectDropdownAgents, arg.KnowledgeID, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectDropdownAgentsRow{}
	for rows.Next() {
		var i SelectDropdownAgentsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.IsConnected); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
