// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: globalConfig.sql

package db

import (
	"context"
)

const getGlobalConfig = `-- name: GetGlobalConfig :one
SELECT id, agent_name, industry_description, guardrail, created_at, updated_at
FROM global_config
WHERE id = true
`

func (q *Queries) GetGlobalConfig(ctx context.Context) (GlobalConfig, error) {
	row := q.db.QueryRow(ctx, getGlobalConfig)
	var i GlobalConfig
	err := row.Scan(
		&i.ID,
		&i.AgentName,
		&i.IndustryDescription,
		&i.Guardrail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGlobalConfig = `-- name: UpdateGlobalConfig :one
UPDATE global_config
SET
    agent_name = $1,
    industry_description = $2,
    guardrail = $3,
    updated_at = now()
WHERE id = true
RETURNING id, agent_name, industry_description, guardrail, created_at, updated_at
`

type UpdateGlobalConfigParams struct {
	AgentName           string `json:"agent_name"`
	IndustryDescription string `json:"industry_description"`
	Guardrail           string `json:"guardrail"`
}

func (q *Queries) UpdateGlobalConfig(ctx context.Context, arg UpdateGlobalConfigParams) (GlobalConfig, error) {
	row := q.db.QueryRow(ctx, updateGlobalConfig, arg.AgentName, arg.IndustryDescription, arg.Guardrail)
	var i GlobalConfig
	err := row.Scan(
		&i.ID,
		&i.AgentName,
		&i.IndustryDescription,
		&i.Guardrail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
