// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: knowledges.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countAllKnowledges = `-- name: CountAllKnowledges :one
SELECT count(*) FROM knowledges_view kv
WHERE (
    $1::text IS NULL
    OR kv.name ILIKE '%' || $1::text || '%'
    OR kv.description ILIKE '%' || $1::text || '%'
)
`

func (q *Queries) CountAllKnowledges(ctx context.Context, search *string) (int64, error) {
	row := q.db.QueryRow(ctx, countAllKnowledges, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKnowledges = `-- name: CountKnowledges :one
SELECT count(*) FROM knowledges_view kv
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR kv.source_type = $1::text
)
AND (
    $2::text IS NULL
    OR kv.name ILIKE '%' || $2::text || '%'
    OR kv.description ILIKE '%' || $2::text || '%'
)
AND (
    $3::uuid IS NULL
    OR EXISTS (
        SELECT 1 FROM knowledge_tags kt
        WHERE kt.knowledge_id = kv.id AND kt.tag_id = $3::uuid
    )
)
`

type CountKnowledgesParams struct {
	SourceType *string    `json:"source_type"`
	Search     *string    `json:"search"`
	TagID      *uuid.UUID `json:"tag_id"`
}

func (q *Queries) CountKnowledges(ctx context.Context, arg CountKnowledgesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countKnowledges, arg.SourceType, arg.Search, arg.TagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKnowledgesByAgentId = `-- name: CountKnowledgesByAgentId :one
SELECT count(*)
FROM knowledges_view kv
JOIN agent_knowledges_view akv
    ON akv.knowledge_id = kv.id
WHERE akv.agent_id = $1
AND (
    $2::text IS NULL
    OR kv.name ILIKE '%' || $2::text || '%'
    OR kv.description ILIKE '%' || $2::text || '%'
)
`

type CountKnowledgesByAgentIdParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Search  *string   `json:"search"`
}

func (q *Queries) CountKnowledgesByAgentId(ctx context.Context, arg CountKnowledgesByAgentIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, countKnowledgesByAgentId, arg.AgentID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertKnowledge = `-- name: InsertKnowledge :one
INSERT INTO knowledges (name, description, source_type, source_uri, is_crawl)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id, name, description, source_type, source_uri, is_crawl, created_at, updated_at
`

type InsertKnowledgeParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	SourceType  string  `json:"source_type"`
	SourceUri   *string `json:"source_uri"`
	IsCrawl     bool    `json:"is_crawl"`
}

type InsertKnowledgeRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	SourceType  string    `json:"source_type"`
	SourceUri   *string   `json:"source_uri"`
	IsCrawl     bool      `json:"is_crawl"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) InsertKnowledge(ctx context.Context, arg InsertKnowledgeParams) (InsertKnowledgeRow, error) {
	row := q.db.QueryRow(ctx, insertKnowledge,
		arg.Name,
		arg.Description,
		arg.SourceType,
		arg.SourceUri,
		arg.IsCrawl,
	)
	var i InsertKnowledgeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.SourceUri,
		&i.IsCrawl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectKnowledgeById = `-- name: SelectKnowledgeById :one
SELECT
    kv.id, kv.name, kv.description, kv.source_type, kv.source_uri, kv.created_at, kv.updated_at, kv.is_crawl,
    (
        SELECT COALESCE(jsonb_agg(jsonb_build_object('id', t.id, 'name', t.name, 'color', t.color) ORDER BY t.name), '[]'::jsonb)
        FROM knowledge_tags kt
        JOIN tags_view t ON t.id = kt.tag_id
        WHERE kt.knowledge_id = kv.id
    )::jsonb AS tags
FROM knowledges_view kv
WHERE kv.id = $1
LIMIT 1
`

type SelectKnowledgeByIdRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	SourceType  string          `json:"source_type"`
	SourceUri   *string         `json:"source_uri"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	IsCrawl     bool            `json:"is_crawl"`
	Tags        json.RawMessage `json:"tags"`
}

func (q *Queries) SelectKnowledgeById(ctx context.Context, id uuid.UUID) (SelectKnowledgeByIdRow, error) {
	row := q.db.QueryRow(ctx, selectKnowledgeById, id)
	var i SelectKnowledgeByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.SourceUri,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsCrawl,
		&i.Tags,
	)
	return i, err
}

const selectKnowledges = `-- name: SelectKnowledges :many
SELECT
    kv.id, kv.name, kv.description, kv.source_type, kv.source_uri, kv.created_at, kv.updated_at, kv.is_crawl,
    (
        SELECT count(*)
        FROM agent_knowledges_view akv
        WHERE akv.knowledge_id = kv.id
    ) AS agents_count,
    (
        SELECT COALESCE(jsonb_agg(jsonb_build_object('id', t.id, 'name', t.name, 'color', t.color) ORDER BY t.name), '[]'::jsonb)
        FROM knowledge_tags kt
        JOIN tags_view t ON t.id = kt.tag_id
        WHERE kt.knowledge_id = kv.id
    )::jsonb AS tags
FROM knowledges_view kv
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR kv.source_type = $1::text
)
AND (
    $2::text IS NULL
    OR kv.name ILIKE '%' || $2::text || '%'
    OR kv.description ILIKE '%' || $2::text || '%'
)
AND (
    $3::uuid IS NULL
    OR EXISTS (
        SELECT 1 FROM knowledge_tags kt
        WHERE kt.knowledge_id = kv.id AND kt.tag_id = $3::uuid
    )
)
ORDER BY
    CASE WHEN $4::text = 'name_asc' THEN name END ASC,
    CASE WHEN $4::text = 'name_desc' THEN name END DESC,
    CASE WHEN $4::text = 'created_asc' THEN created_at END ASC,
    CASE WHEN $4::text = 'created_desc' THEN created_at END DESC,
    CASE WHEN $4::text = 'source_type_asc' THEN source_type END ASC,
    CASE WHEN $4::text = 'source_type_desc' THEN source_type END DESC,
    created_at DESC
LIMIT $6 OFFSET $5
`

type SelectKnowledgesParams struct {
	SourceType *string    `json:"source_type"`
	Search     *string    `json:"search"`
	TagID      *uuid.UUID `json:"tag_id"`
	Sort       *string    `json:"sort"`
	Offset     int32      `json:"offset"`
	Limit      int32      `json:"limit"`
}

type SelectKnowledgesRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	SourceType  string          `json:"source_type"`
	SourceUri   *string         `json:"source_uri"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	IsCrawl     bool            `json:"is_crawl"`
	AgentsCount int64           `json:"agents_count"`
	Tags        json.RawMessage `json:"tags"`
}

func (q *Queries) SelectKnowledges(ctx context.Context, arg SelectKnowledgesParams) ([]SelectKnowledgesRow, error) {
	rows, err := q.db.Query(ctx, selectKnowledges,
		arg.SourceType,
		arg.Search,
		arg.TagID,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectKnowledgesRow{}
	for rows.Next() {
		var i SelectKnowledgesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SourceType,
			&i.SourceUri,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsCrawl,
			&i.AgentsCount,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectKnowledgesByAgentId = `-- name: SelectKnowledgesByAgentId :many
SELECT
    kv.id, kv.name, kv.description, kv.source_type, kv.source_uri, kv.created_at, kv.updated_at, kv.is_crawl,
    akv.status
FROM knowledges_view kv
JOIN agent_knowledges_view akv
    ON akv.knowledge_id = kv.id
WHERE akv.agent_id = $1
AND (
    $2::text IS NULL
    OR kv.name ILIKE '%' || $2::text || '%'
    OR kv.description ILIKE '%' || $2::text || '%'
)
ORDER BY
    CASE WHEN $3::text = 'name_asc' THEN kv.name END ASC,
    CASE WHEN $3::text = 'name_desc' THEN kv.name END DESC,
    CASE
        WHEN $3::text = 'created_asc' THEN kv.created_at
    END ASC,
    CASE
        WHEN $3::text = 'created_desc' THEN kv.created_at
    END DESC,
    kv.created_at DESC
LIMIT $5 OFFSET $4
`

type SelectKnowledgesByAgentIdParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Search  *string   `json:"search"`
	Sort    *string   `json:"sort"`
	Offset  int32     `json:"offset"`
	Limit   int32     `json:"limit"`
}

type SelectKnowledgesByAgentIdRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	SourceType  string    `json:"source_type"`
	SourceUri   *string   `json:"source_uri"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	IsCrawl     bool      `json:"is_crawl"`
	Status      string    `json:"status"`
}

func (q *Queries) SelectKnowledgesByAgentId(ctx context.Context, arg SelectKnowledgesByAgentIdParams) ([]SelectKnowledgesByAgentIdRow, error) {
	rows, err := q.db.Query(ctx, selectKnowledgesByAgentId,
		arg.AgentID,
		arg.Search,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectKnowledgesByAgentIdRow{}
	for rows.Next() {
		var i SelectKnowledgesByAgentIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SourceType,
			&i.SourceUri,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsCrawl,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectKnowledgesWithAgentStatus = `-- name: SelectKnowledgesWithAgentStatus :many
SELECT
    kv.id, kv.name, kv.description, kv.source_type, kv.source_uri, kv.created_at, kv.updated_at, kv.is_crawl,
    (akv.id IS NOT NULL)::bool AS connected
FROM knowledges_view kv
LEFT JOIN agent_knowledges_view akv
    ON akv.knowledge_id = kv.id
    AND akv.agent_id = $1
WHERE (
    $2::text IS NULL
    OR kv.name ILIKE '%' || $2::text || '%'
    OR kv.description ILIKE '%' || $2::text || '%'
)
ORDER BY
    connected DESC,
    CASE WHEN $3::text = 'name_asc' THEN kv.name END ASC,
    CASE WHEN $3::text = 'name_desc' THEN kv.name END DESC,
    CASE
        WHEN $3::text = 'created_asc' THEN kv.created_at
    END ASC,
    CASE
        WHEN $3::text = 'created_desc' THEN kv.created_at
    END DESC,
    kv.created_at DESC
LIMIT $5 OFFSET $4
`

type SelectKnowledgesWithAgentStatusParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Search  *string   `json:"search"`
	Sort    *string   `json:"sort"`
	Offset  int32     `json:"offset"`
	Limit   int32     `json:"limit"`
}

type SelectKnowledgesWithAgentStatusRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	SourceType  string    `json:"source_type"`
	SourceUri   *string   `json:"source_uri"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	IsCrawl     bool      `json:"is_crawl"`
	Connected   bool      `json:"connected"`
}

func (q *Queries) SelectKnowledgesWithAgentStatus(ctx context.Context, arg SelectKnowledgesWithAgentStatusParams) ([]SelectKnowledgesWithAgentStatusRow, error) {
	rows, err := q.db.Query(ctx, selectKnowledgesWithAgentStatus,
		arg.AgentID,
		arg.Search,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectKnowledgesWithAgentStatusRow{}
	for rows.Next() {
		var i SelectKnowledgesWithAgentStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SourceType,
			&i.SourceUri,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsCrawl,
			&i.Connected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteKnowledge = `-- name: SoftDeleteKnowledge :execrows
UPDATE knowledges
SET deleted_at = now()
WHERE
    deleted_at IS NULL
    AND id = $1
`

func (q *Queries) SoftDeleteKnowledge(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteKnowledge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateKnowledge = `-- name: UpdateKnowledge :one
UPDATE knowledges
SET
    name = $1,
    description = $2,
    updated_at = now()
WHERE
    deleted_at IS NULL
    AND id = $3
RETURNING
    id, name, description, source_type, source_uri, created_at, updated_at
`

type UpdateKnowledgeParams struct {
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	ID          uuid.UUID `json:"id"`
}

type UpdateKnowledgeRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	SourceType  string    `json:"source_type"`
	SourceUri   *string   `json:"source_uri"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateKnowledge(ctx context.Context, arg UpdateKnowledgeParams) (UpdateKnowledgeRow, error) {
	row := q.db.QueryRow(ctx, updateKnowledge, arg.Name, arg.Description, arg.ID)
	var i UpdateKnowledgeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.SourceUri,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
