// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: knowledges.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAllKnowledges = `-- name: CountAllKnowledges :one
SELECT count(*) FROM knowledges_view
`

func (q *Queries) CountAllKnowledges(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllKnowledges)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKnowledges = `-- name: CountKnowledges :one
SELECT count(*) FROM knowledges_view
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR source_type = $1::text
)
`

func (q *Queries) CountKnowledges(ctx context.Context, sourceType *string) (int64, error) {
	row := q.db.QueryRow(ctx, countKnowledges, sourceType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKnowledgesByAgentId = `-- name: CountKnowledgesByAgentId :one
SELECT count(*)
FROM knowledges_view kv
JOIN agent_knowledges_view akv
    ON akv.knowledge_id = kv.id
WHERE akv.agent_id = $1
`

func (q *Queries) CountKnowledgesByAgentId(ctx context.Context, agentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countKnowledgesByAgentId, agentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertKnowledge = `-- name: InsertKnowledge :one
INSERT INTO knowledges (name, description, source_type, source_uri)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id, name, description, source_type, source_uri, created_at, updated_at
`

type InsertKnowledgeParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	SourceType  string  `json:"source_type"`
	SourceUri   *string `json:"source_uri"`
}

type InsertKnowledgeRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	SourceType  string    `json:"source_type"`
	SourceUri   *string   `json:"source_uri"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) InsertKnowledge(ctx context.Context, arg InsertKnowledgeParams) (InsertKnowledgeRow, error) {
	row := q.db.QueryRow(ctx, insertKnowledge,
		arg.Name,
		arg.Description,
		arg.SourceType,
		arg.SourceUri,
	)
	var i InsertKnowledgeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.SourceUri,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectKnowledgeById = `-- name: SelectKnowledgeById :one
SELECT id, name, description, source_type, source_uri, created_at, updated_at FROM knowledges_view
WHERE id = $1
LIMIT 1
`

func (q *Queries) SelectKnowledgeById(ctx context.Context, id uuid.UUID) (KnowledgesView, error) {
	row := q.db.QueryRow(ctx, selectKnowledgeById, id)
	var i KnowledgesView
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.SourceUri,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectKnowledges = `-- name: SelectKnowledges :many
SELECT
    kv.id, kv.name, kv.description, kv.source_type, kv.source_uri, kv.created_at, kv.updated_at,
    (
        SELECT count(*)
        FROM agent_knowledges_view akv
        WHERE akv.knowledge_id = kv.id
    ) AS agents_count
FROM knowledges_view kv
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR kv.source_type = $1::text
)
ORDER BY
    CASE WHEN $2::text = 'name_asc' THEN name END ASC,
    CASE WHEN $2::text = 'name_desc' THEN name END DESC,
    CASE WHEN $2::text = 'created_asc' THEN created_at END ASC,
    CASE WHEN $2::text = 'created_desc' THEN created_at END DESC,
    created_at DESC
LIMIT $4 OFFSET $3
`

type SelectKnowledgesParams struct {
	SourceType *string `json:"source_type"`
	Sort       *string `json:"sort"`
	Offset     int32   `json:"offset"`
	Limit      int32   `json:"limit"`
}

type SelectKnowledgesRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	SourceType  string    `json:"source_type"`
	SourceUri   *string   `json:"source_uri"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	AgentsCount int64     `json:"agents_count"`
}

func (q *Queries) SelectKnowledges(ctx context.Context, arg SelectKnowledgesParams) ([]SelectKnowledgesRow, error) {
	rows, err := q.db.Query(ctx, selectKnowledges,
		arg.SourceType,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectKnowledgesRow{}
	for rows.Next() {
		var i SelectKnowledgesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SourceType,
			&i.SourceUri,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AgentsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectKnowledgesByAgentId = `-- name: SelectKnowledgesByAgentId :many
SELECT
    kv.id, kv.name, kv.description, kv.source_type, kv.source_uri, kv.created_at, kv.updated_at,
    akv.status
FROM knowledges_view kv
JOIN agent_knowledges_view akv
    ON akv.knowledge_id = kv.id
WHERE akv.agent_id = $1
ORDER BY
    CASE WHEN $2::text = 'name_asc' THEN kv.name END ASC,
    CASE WHEN $2::text = 'name_desc' THEN kv.name END DESC,
    CASE
        WHEN $2::text = 'created_asc' THEN kv.created_at
    END ASC,
    CASE
        WHEN $2::text = 'created_desc' THEN kv.created_at
    END DESC,
    kv.created_at DESC
LIMIT $4 OFFSET $3
`

type SelectKnowledgesByAgentIdParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Sort    *string   `json:"sort"`
	Offset  int32     `json:"offset"`
	Limit   int32     `json:"limit"`
}

type SelectKnowledgesByAgentIdRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	SourceType  string    `json:"source_type"`
	SourceUri   *string   `json:"source_uri"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Status      string    `json:"status"`
}

func (q *Queries) SelectKnowledgesByAgentId(ctx context.Context, arg SelectKnowledgesByAgentIdParams) ([]SelectKnowledgesByAgentIdRow, error) {
	rows, err := q.db.Query(ctx, selectKnowledgesByAgentId,
		arg.AgentID,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectKnowledgesByAgentIdRow{}
	for rows.Next() {
		var i SelectKnowledgesByAgentIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SourceType,
			&i.SourceUri,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectKnowledgesWithAgentStatus = `-- name: SelectKnowledgesWithAgentStatus :many
SELECT
    kv.id, kv.name, kv.description, kv.source_type, kv.source_uri, kv.created_at, kv.updated_at,
    (akv.id IS NOT NULL)::bool AS connected
FROM knowledges_view kv
LEFT JOIN agent_knowledges_view akv
    ON akv.knowledge_id = kv.id
    AND akv.agent_id = $1
ORDER BY
    connected DESC,
    CASE WHEN $2::text = 'name_asc' THEN kv.name END ASC,
    CASE WHEN $2::text = 'name_desc' THEN kv.name END DESC,
    CASE
        WHEN $2::text = 'created_asc' THEN kv.created_at
    END ASC,
    CASE
        WHEN $2::text = 'created_desc' THEN kv.created_at
    END DESC,
    kv.created_at DESC
LIMIT $4 OFFSET $3
`

type SelectKnowledgesWithAgentStatusParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Sort    *string   `json:"sort"`
	Offset  int32     `json:"offset"`
	Limit   int32     `json:"limit"`
}

type SelectKnowledgesWithAgentStatusRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	SourceType  string    `json:"source_type"`
	SourceUri   *string   `json:"source_uri"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Connected   bool      `json:"connected"`
}

func (q *Queries) SelectKnowledgesWithAgentStatus(ctx context.Context, arg SelectKnowledgesWithAgentStatusParams) ([]SelectKnowledgesWithAgentStatusRow, error) {
	rows, err := q.db.Query(ctx, selectKnowledgesWithAgentStatus,
		arg.AgentID,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectKnowledgesWithAgentStatusRow{}
	for rows.Next() {
		var i SelectKnowledgesWithAgentStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SourceType,
			&i.SourceUri,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Connected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteKnowledge = `-- name: SoftDeleteKnowledge :execrows
UPDATE knowledges
SET deleted_at = now()
WHERE
    deleted_at IS NULL
    AND id = $1
`

func (q *Queries) SoftDeleteKnowledge(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteKnowledge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateKnowledge = `-- name: UpdateKnowledge :one
UPDATE knowledges
SET
    name = $1,
    description = $2,
    updated_at = now()
WHERE
    deleted_at IS NULL
    AND id = $3
RETURNING
    id, name, description, source_type, source_uri, created_at, updated_at
`

type UpdateKnowledgeParams struct {
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	ID          uuid.UUID `json:"id"`
}

type UpdateKnowledgeRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	SourceType  string    `json:"source_type"`
	SourceUri   *string   `json:"source_uri"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateKnowledge(ctx context.Context, arg UpdateKnowledgeParams) (UpdateKnowledgeRow, error) {
	row := q.db.QueryRow(ctx, updateKnowledge, arg.Name, arg.Description, arg.ID)
	var i UpdateKnowledgeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.SourceUri,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
