// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: knowledges.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertKnowledge = `-- name: InsertKnowledge :one
INSERT INTO knowledges (name, description, source_type, source_uri)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, description, source_type, source_uri, created_at, updated_at, deleted_at
`

type InsertKnowledgeParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	SourceType  string  `json:"source_type"`
	SourceUri   *string `json:"source_uri"`
}

func (q *Queries) InsertKnowledge(ctx context.Context, arg InsertKnowledgeParams) (Knowledge, error) {
	row := q.db.QueryRow(ctx, insertKnowledge,
		arg.Name,
		arg.Description,
		arg.SourceType,
		arg.SourceUri,
	)
	var i Knowledge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.SourceUri,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectKnowledgeById = `-- name: SelectKnowledgeById :one
SELECT id, name, description, source_type, source_uri, created_at, updated_at, deleted_at FROM knowledges
WHERE
    deleted_at IS NULL
    AND id = $1
LIMIT 1
`

func (q *Queries) SelectKnowledgeById(ctx context.Context, id uuid.UUID) (Knowledge, error) {
	row := q.db.QueryRow(ctx, selectKnowledgeById, id)
	var i Knowledge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.SourceUri,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectKnowledges = `-- name: SelectKnowledges :many
SELECT id, name, description, source_type, source_uri, created_at, updated_at, deleted_at FROM knowledges
WHERE
    deleted_at IS NULL
    AND (
        $1::text IS NULL
        OR $1::text = ''
        OR source_type = $1::text
    )
ORDER BY
    CASE WHEN $2::text = 'name_asc' THEN name END ASC,
    CASE WHEN $2::text = 'name_desc' THEN name END DESC,
    CASE WHEN $2::text = 'created_asc' THEN created_at END ASC,
    CASE WHEN $2::text = 'created_desc' THEN created_at END DESC,
    created_at DESC
LIMIT coalesce($4, 10) OFFSET coalesce($3, 0)
`

type SelectKnowledgesParams struct {
	SourceType *string     `json:"source_type"`
	Sort       *string     `json:"sort"`
	Offset     interface{} `json:"offset"`
	Limit      interface{} `json:"limit"`
}

func (q *Queries) SelectKnowledges(ctx context.Context, arg SelectKnowledgesParams) ([]Knowledge, error) {
	rows, err := q.db.Query(ctx, selectKnowledges,
		arg.SourceType,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Knowledge{}
	for rows.Next() {
		var i Knowledge
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SourceType,
			&i.SourceUri,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteKnowledge = `-- name: SoftDeleteKnowledge :execrows
UPDATE knowledges
SET deleted_at = now()
WHERE
    deleted_at IS NULL
    AND id = $1
`

func (q *Queries) SoftDeleteKnowledge(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteKnowledge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateKnowledge = `-- name: UpdateKnowledge :one
UPDATE knowledges
SET
    name = $1,
    description = $2,
    updated_at = now()
WHERE
    deleted_at IS NULL
    AND id = $3
RETURNING id, name, description, source_type, source_uri, created_at, updated_at, deleted_at
`

type UpdateKnowledgeParams struct {
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateKnowledge(ctx context.Context, arg UpdateKnowledgeParams) (Knowledge, error) {
	row := q.db.QueryRow(ctx, updateKnowledge, arg.Name, arg.Description, arg.ID)
	var i Knowledge
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SourceType,
		&i.SourceUri,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
