// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_tools.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countMcpToolsByMcpId = `-- name: CountMcpToolsByMcpId :one
SELECT count(*) FROM mcp_tools_view
WHERE mcp_id = $1
`

func (q *Queries) CountMcpToolsByMcpId(ctx context.Context, mcpID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMcpToolsByMcpId, mcpID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertMcpTool = `-- name: InsertMcpTool :one
INSERT INTO mcp_tools (mcp_id, name, description, target_uri, input_schema)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id, mcp_id, name, description, target_uri, input_schema, created_at, updated_at
`

type InsertMcpToolParams struct {
	McpID       uuid.UUID       `json:"mcp_id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	TargetUri   string          `json:"target_uri"`
	InputSchema json.RawMessage `json:"input_schema"`
}

type InsertMcpToolRow struct {
	ID          uuid.UUID       `json:"id"`
	McpID       uuid.UUID       `json:"mcp_id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	TargetUri   string          `json:"target_uri"`
	InputSchema json.RawMessage `json:"input_schema"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) InsertMcpTool(ctx context.Context, arg InsertMcpToolParams) (InsertMcpToolRow, error) {
	row := q.db.QueryRow(ctx, insertMcpTool,
		arg.McpID,
		arg.Name,
		arg.Description,
		arg.TargetUri,
		arg.InputSchema,
	)
	var i InsertMcpToolRow
	err := row.Scan(
		&i.ID,
		&i.McpID,
		&i.Name,
		&i.Description,
		&i.TargetUri,
		&i.InputSchema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectMcpToolsByMcpId = `-- name: SelectMcpToolsByMcpId :many
SELECT id, mcp_id, name, description, target_uri, input_schema, created_at, updated_at FROM mcp_tools_view
WHERE mcp_id = $1
ORDER BY name ASC
`

func (q *Queries) SelectMcpToolsByMcpId(ctx context.Context, mcpID uuid.UUID) ([]McpToolsView, error) {
	rows, err := q.db.Query(ctx, selectMcpToolsByMcpId, mcpID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpToolsView{}
	for rows.Next() {
		var i McpToolsView
		if err := rows.Scan(
			&i.ID,
			&i.McpID,
			&i.Name,
			&i.Description,
			&i.TargetUri,
			&i.InputSchema,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMcpToolsByMcpId = `-- name: SoftDeleteMcpToolsByMcpId :execrows
UPDATE mcp_tools
SET deleted_at = now()
WHERE
    deleted_at IS NULL
    AND mcp_id = $1
`

func (q *Queries) SoftDeleteMcpToolsByMcpId(ctx context.Context, mcpID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMcpToolsByMcpId, mcpID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
