// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcps.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteMcp = `-- name: DeleteMcp :execrows
DELETE FROM mcps
WHERE
    deleted_at IS NULL
    AND id = $1
`

func (q *Queries) DeleteMcp(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMcp, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertMcp = `-- name: InsertMcp :one
INSERT INTO mcps (agent_id, name, description, uri)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, description, uri, agent_id, created_at, updated_at, deleted_at
`

type InsertMcpParams struct {
	AgentID     uuid.UUID `json:"agent_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Uri         string    `json:"uri"`
}

func (q *Queries) InsertMcp(ctx context.Context, arg InsertMcpParams) (Mcp, error) {
	row := q.db.QueryRow(ctx, insertMcp,
		arg.AgentID,
		arg.Name,
		arg.Description,
		arg.Uri,
	)
	var i Mcp
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Uri,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectMcpById = `-- name: SelectMcpById :one
SELECT id, name, description, uri, agent_id, created_at, updated_at, deleted_at FROM mcps
WHERE
    deleted_at IS NULL
    AND id = $1
LIMIT 1
`

func (q *Queries) SelectMcpById(ctx context.Context, id uuid.UUID) (Mcp, error) {
	row := q.db.QueryRow(ctx, selectMcpById, id)
	var i Mcp
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Uri,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const selectMcps = `-- name: SelectMcps :many
SELECT id, name, description, uri, agent_id, created_at, updated_at, deleted_at FROM mcps
WHERE deleted_at IS NULL
ORDER BY
    CASE WHEN $1::text = 'name_asc' THEN name END ASC,
    CASE WHEN $1::text = 'name_desc' THEN name END DESC,
    CASE WHEN $1::text = 'created_asc' THEN created_at END ASC,
    CASE WHEN $1::text = 'created_desc' THEN created_at END DESC,
    created_at DESC
LIMIT coalesce($3, 10) OFFSET coalesce($2, 0)
`

type SelectMcpsParams struct {
	Sort   *string     `json:"sort"`
	Offset interface{} `json:"offset"`
	Limit  interface{} `json:"limit"`
}

func (q *Queries) SelectMcps(ctx context.Context, arg SelectMcpsParams) ([]Mcp, error) {
	rows, err := q.db.Query(ctx, selectMcps, arg.Sort, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mcp{}
	for rows.Next() {
		var i Mcp
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Uri,
			&i.AgentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMcp = `-- name: UpdateMcp :one
UPDATE mcps
SET
    name = $1,
    description = $2,
    updated_at = now()
WHERE
    deleted_at IS NULL
    AND id = $3
RETURNING id, name, description, uri, agent_id, created_at, updated_at, deleted_at
`

type UpdateMcpParams struct {
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) UpdateMcp(ctx context.Context, arg UpdateMcpParams) (Mcp, error) {
	row := q.db.QueryRow(ctx, updateMcp, arg.Name, arg.Description, arg.ID)
	var i Mcp
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Uri,
		&i.AgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
