// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcps.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countMcps = `-- name: CountMcps :one
SELECT count(*) FROM mcps_view m
WHERE (
    $1::text IS NULL
    OR m.name ILIKE '%' || $1::text || '%'
    OR m.description ILIKE '%' || $1::text || '%'
)
AND (
    $2::uuid IS NULL
    OR EXISTS (
        SELECT 1 FROM mcp_tags mt
        WHERE mt.mcp_id = m.id AND mt.tag_id = $2::uuid
    )
)
`

type CountMcpsParams struct {
	Search *string    `json:"search"`
	TagID  *uuid.UUID `json:"tag_id"`
}

func (q *Queries) CountMcps(ctx context.Context, arg CountMcpsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMcps, arg.Search, arg.TagID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMcpsByAgentId = `-- name: CountMcpsByAgentId :one
SELECT count(*)
FROM mcps_view m
JOIN agent_mcps_view amv
    ON amv.mcp_id = m.id
WHERE amv.agent_id = $1
AND (
    $2::text IS NULL
    OR m.name ILIKE '%' || $2::text || '%'
    OR m.description ILIKE '%' || $2::text || '%'
)
`

type CountMcpsByAgentIdParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Search  *string   `json:"search"`
}

func (q *Queries) CountMcpsByAgentId(ctx context.Context, arg CountMcpsByAgentIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMcpsByAgentId, arg.AgentID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertMcp = `-- name: InsertMcp :one
INSERT INTO mcps (name, description, uri, headers)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, description, uri, headers, created_at, updated_at
`

type InsertMcpParams struct {
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Uri         string          `json:"uri"`
	Headers     json.RawMessage `json:"headers"`
}

type InsertMcpRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Uri         string          `json:"uri"`
	Headers     json.RawMessage `json:"headers"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) InsertMcp(ctx context.Context, arg InsertMcpParams) (InsertMcpRow, error) {
	row := q.db.QueryRow(ctx, insertMcp,
		arg.Name,
		arg.Description,
		arg.Uri,
		arg.Headers,
	)
	var i InsertMcpRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Uri,
		&i.Headers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectMcpById = `-- name: SelectMcpById :one
SELECT
    m.id, m.name, m.description, m.uri, m.created_at, m.updated_at, m.headers,
    (
        SELECT COALESCE(jsonb_agg(jsonb_build_object('id', t.id, 'name', t.name, 'color', t.color) ORDER BY t.name), '[]'::jsonb)
        FROM mcp_tags mt
        JOIN tags_view t ON t.id = mt.tag_id
        WHERE mt.mcp_id = m.id
    )::jsonb AS tags
FROM mcps_view m
WHERE m.id = $1
LIMIT 1
`

type SelectMcpByIdRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Uri         string          `json:"uri"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	Headers     json.RawMessage `json:"headers"`
	Tags        json.RawMessage `json:"tags"`
}

func (q *Queries) SelectMcpById(ctx context.Context, id uuid.UUID) (SelectMcpByIdRow, error) {
	row := q.db.QueryRow(ctx, selectMcpById, id)
	var i SelectMcpByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Uri,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Headers,
		&i.Tags,
	)
	return i, err
}

const selectMcps = `-- name: SelectMcps :many
SELECT
    m.id, m.name, m.description, m.uri, m.created_at, m.updated_at, m.headers,
    (
        SELECT count(*)
        FROM mcp_tools AS t
        WHERE t.mcp_id = m.id AND t.deleted_at IS NULL
    ) AS tools_count,
    (
        SELECT count(*)
        FROM agent_mcps_view amv
        WHERE amv.mcp_id = m.id
    ) AS agents_count,
    (
        SELECT COALESCE(jsonb_agg(jsonb_build_object('id', t.id, 'name', t.name, 'color', t.color) ORDER BY t.name), '[]'::jsonb)
        FROM mcp_tags mt
        JOIN tags_view t ON t.id = mt.tag_id
        WHERE mt.mcp_id = m.id
    )::jsonb AS tags
FROM mcps_view AS m
WHERE (
    $1::text IS NULL
    OR m.name ILIKE '%' || $1::text || '%'
    OR m.description ILIKE '%' || $1::text || '%'
)
AND (
    $2::uuid IS NULL
    OR EXISTS (
        SELECT 1 FROM mcp_tags mt
        WHERE mt.mcp_id = m.id AND mt.tag_id = $2::uuid
    )
)
ORDER BY
    CASE WHEN $3::text = 'name_asc' THEN m.name END ASC,
    CASE WHEN $3::text = 'name_desc' THEN m.name END DESC,
    CASE WHEN $3::text = 'created_asc' THEN m.created_at END ASC,
    CASE
        WHEN $3::text = 'created_desc' THEN m.created_at
    END DESC,
    CASE WHEN $3::text = 'tools_count_asc' THEN (
        SELECT count(*) FROM mcp_tools AS t
        WHERE t.mcp_id = m.id AND t.deleted_at IS NULL
    ) END ASC,
    CASE WHEN $3::text = 'tools_count_desc' THEN (
        SELECT count(*) FROM mcp_tools AS t
        WHERE t.mcp_id = m.id AND t.deleted_at IS NULL
    ) END DESC,
    m.created_at DESC
LIMIT $5 OFFSET $4
`

type SelectMcpsParams struct {
	Search *string    `json:"search"`
	TagID  *uuid.UUID `json:"tag_id"`
	Sort   *string    `json:"sort"`
	Offset int32      `json:"offset"`
	Limit  int32      `json:"limit"`
}

type SelectMcpsRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Uri         string          `json:"uri"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	Headers     json.RawMessage `json:"headers"`
	ToolsCount  int64           `json:"tools_count"`
	AgentsCount int64           `json:"agents_count"`
	Tags        json.RawMessage `json:"tags"`
}

func (q *Queries) SelectMcps(ctx context.Context, arg SelectMcpsParams) ([]SelectMcpsRow, error) {
	rows, err := q.db.Query(ctx, selectMcps,
		arg.Search,
		arg.TagID,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectMcpsRow{}
	for rows.Next() {
		var i SelectMcpsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Uri,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headers,
			&i.ToolsCount,
			&i.AgentsCount,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectMcpsByAgentId = `-- name: SelectMcpsByAgentId :many
SELECT
    m.id, m.name, m.description, m.uri, m.created_at, m.updated_at, m.headers,
    (
        SELECT count(*)
        FROM mcp_tools AS t
        WHERE t.mcp_id = m.id AND t.deleted_at IS NULL
    ) AS tools_count
FROM mcps_view AS m
JOIN agent_mcps_view amv
    ON amv.mcp_id = m.id
WHERE amv.agent_id = $1
AND (
    $2::text IS NULL
    OR m.name ILIKE '%' || $2::text || '%'
    OR m.description ILIKE '%' || $2::text || '%'
)
ORDER BY
    CASE WHEN $3::text = 'name_asc' THEN m.name END ASC,
    CASE WHEN $3::text = 'name_desc' THEN m.name END DESC,
    CASE WHEN $3::text = 'created_asc' THEN m.created_at END ASC,
    CASE
        WHEN $3::text = 'created_desc' THEN m.created_at
    END DESC,
    m.created_at DESC
LIMIT $5 OFFSET $4
`

type SelectMcpsByAgentIdParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Search  *string   `json:"search"`
	Sort    *string   `json:"sort"`
	Offset  int32     `json:"offset"`
	Limit   int32     `json:"limit"`
}

type SelectMcpsByAgentIdRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Uri         string          `json:"uri"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	Headers     json.RawMessage `json:"headers"`
	ToolsCount  int64           `json:"tools_count"`
}

func (q *Queries) SelectMcpsByAgentId(ctx context.Context, arg SelectMcpsByAgentIdParams) ([]SelectMcpsByAgentIdRow, error) {
	rows, err := q.db.Query(ctx, selectMcpsByAgentId,
		arg.AgentID,
		arg.Search,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectMcpsByAgentIdRow{}
	for rows.Next() {
		var i SelectMcpsByAgentIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Uri,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headers,
			&i.ToolsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectMcpsWithAgentStatus = `-- name: SelectMcpsWithAgentStatus :many
SELECT
    m.id, m.name, m.description, m.uri, m.created_at, m.updated_at, m.headers,
    (
        SELECT count(*)
        FROM mcp_tools AS t
        WHERE t.mcp_id = m.id AND t.deleted_at IS NULL
    ) AS tools_count,
    (amv.id IS NOT NULL)::bool AS connected
FROM mcps_view AS m
LEFT JOIN agent_mcps_view amv
    ON amv.mcp_id = m.id
    AND amv.agent_id = $1
WHERE (
    $2::text IS NULL
    OR m.name ILIKE '%' || $2::text || '%'
    OR m.description ILIKE '%' || $2::text || '%'
)
ORDER BY
    connected DESC,
    CASE WHEN $3::text = 'name_asc' THEN m.name END ASC,
    CASE WHEN $3::text = 'name_desc' THEN m.name END DESC,
    CASE WHEN $3::text = 'created_asc' THEN m.created_at END ASC,
    CASE
        WHEN $3::text = 'created_desc' THEN m.created_at
    END DESC,
    m.created_at DESC
LIMIT $5 OFFSET $4
`

type SelectMcpsWithAgentStatusParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	Search  *string   `json:"search"`
	Sort    *string   `json:"sort"`
	Offset  int32     `json:"offset"`
	Limit   int32     `json:"limit"`
}

type SelectMcpsWithAgentStatusRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Uri         string          `json:"uri"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	Headers     json.RawMessage `json:"headers"`
	ToolsCount  int64           `json:"tools_count"`
	Connected   bool            `json:"connected"`
}

func (q *Queries) SelectMcpsWithAgentStatus(ctx context.Context, arg SelectMcpsWithAgentStatusParams) ([]SelectMcpsWithAgentStatusRow, error) {
	rows, err := q.db.Query(ctx, selectMcpsWithAgentStatus,
		arg.AgentID,
		arg.Search,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectMcpsWithAgentStatusRow{}
	for rows.Next() {
		var i SelectMcpsWithAgentStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Uri,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Headers,
			&i.ToolsCount,
			&i.Connected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMcp = `-- name: SoftDeleteMcp :execrows
UPDATE mcps
SET deleted_at = now()
WHERE
    deleted_at IS NULL
    AND id = $1
`

func (q *Queries) SoftDeleteMcp(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMcp, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMcp = `-- name: UpdateMcp :one
UPDATE mcps
SET
    name = $1,
    description = $2,
    uri = $3,
    headers = $4,
    updated_at = now()
WHERE
    deleted_at IS NULL
    AND id = $5
RETURNING id, name, description, uri, headers, created_at, updated_at
`

type UpdateMcpParams struct {
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Uri         string          `json:"uri"`
	Headers     json.RawMessage `json:"headers"`
	ID          uuid.UUID       `json:"id"`
}

type UpdateMcpRow struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Uri         string          `json:"uri"`
	Headers     json.RawMessage `json:"headers"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) UpdateMcp(ctx context.Context, arg UpdateMcpParams) (UpdateMcpRow, error) {
	row := q.db.QueryRow(ctx, updateMcp,
		arg.Name,
		arg.Description,
		arg.Uri,
		arg.Headers,
		arg.ID,
	)
	var i UpdateMcpRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Uri,
		&i.Headers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
