// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcps.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMcps = `-- name: CountMcps :one
SELECT count(*) FROM mcps_view
`

func (q *Queries) CountMcps(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMcps)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertMcp = `-- name: InsertMcp :one
INSERT INTO mcps (agent_id, name, description, uri)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, agent_id, name, description, uri, created_at, updated_at
`

type InsertMcpParams struct {
	AgentID     uuid.UUID `json:"agent_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Uri         string    `json:"uri"`
}

type InsertMcpRow struct {
	ID          uuid.UUID `json:"id"`
	AgentID     uuid.UUID `json:"agent_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Uri         string    `json:"uri"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) InsertMcp(ctx context.Context, arg InsertMcpParams) (InsertMcpRow, error) {
	row := q.db.QueryRow(ctx, insertMcp,
		arg.AgentID,
		arg.Name,
		arg.Description,
		arg.Uri,
	)
	var i InsertMcpRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Name,
		&i.Description,
		&i.Uri,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectMcpById = `-- name: SelectMcpById :one
SELECT id, agent_id, name, description, uri, created_at, updated_at FROM mcps_view
WHERE id = $1
LIMIT 1
`

func (q *Queries) SelectMcpById(ctx context.Context, id uuid.UUID) (McpsView, error) {
	row := q.db.QueryRow(ctx, selectMcpById, id)
	var i McpsView
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Name,
		&i.Description,
		&i.Uri,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectMcps = `-- name: SelectMcps :many
SELECT id, agent_id, name, description, uri, created_at, updated_at FROM mcps_view
ORDER BY
    CASE WHEN $1::text = 'name_asc' THEN name END ASC,
    CASE WHEN $1::text = 'name_desc' THEN name END DESC,
    CASE WHEN $1::text = 'created_asc' THEN created_at END ASC,
    CASE WHEN $1::text = 'created_desc' THEN created_at END DESC,
    created_at DESC
LIMIT $3 OFFSET $2
`

type SelectMcpsParams struct {
	Sort   *string `json:"sort"`
	Offset int32   `json:"offset"`
	Limit  int32   `json:"limit"`
}

func (q *Queries) SelectMcps(ctx context.Context, arg SelectMcpsParams) ([]McpsView, error) {
	rows, err := q.db.Query(ctx, selectMcps, arg.Sort, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpsView{}
	for rows.Next() {
		var i McpsView
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Name,
			&i.Description,
			&i.Uri,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMcp = `-- name: SoftDeleteMcp :execrows
UPDATE mcps
SET deleted_at = now()
WHERE
    deleted_at IS NULL
    AND id = $1
`

func (q *Queries) SoftDeleteMcp(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMcp, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMcp = `-- name: UpdateMcp :one
UPDATE mcps
SET
    name = $1,
    description = $2,
    updated_at = now()
WHERE
    deleted_at IS NULL
    AND id = $3
RETURNING id, agent_id, name, description, uri, created_at, updated_at
`

type UpdateMcpParams struct {
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	ID          uuid.UUID `json:"id"`
}

type UpdateMcpRow struct {
	ID          uuid.UUID `json:"id"`
	AgentID     uuid.UUID `json:"agent_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Uri         string    `json:"uri"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateMcp(ctx context.Context, arg UpdateMcpParams) (UpdateMcpRow, error) {
	row := q.db.QueryRow(ctx, updateMcp, arg.Name, arg.Description, arg.ID)
	var i UpdateMcpRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Name,
		&i.Description,
		&i.Uri,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
