// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (conversation_id, role, content, attachments, data)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type InsertMessageParams struct {
	ConversationID uuid.UUID       `json:"conversation_id"`
	Role           MessageRole     `json:"role"`
	Content        *string         `json:"content"`
	Attachments    json.RawMessage `json:"attachments"`
	Data           json.RawMessage `json:"data"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.Attachments,
		arg.Data,
	)
	return err
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT id, conversation_id, role, content, attachments, data, created_at
FROM messages
WHERE conversation_id = $1
ORDER BY created_at
`

func (q *Queries) ListMessagesByConversation(ctx context.Context, conversationID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Attachments,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
