// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AgentCommunicationStyle string

const (
	AgentCommunicationStyleEXPERTADVISOR       AgentCommunicationStyle = "EXPERT_ADVISOR"
	AgentCommunicationStyleEMPATHETICGUIDE     AgentCommunicationStyle = "EMPATHETIC_GUIDE"
	AgentCommunicationStyleEFFICIENTCONCIERGE  AgentCommunicationStyle = "EFFICIENT_CONCIERGE"
	AgentCommunicationStyleEDUCATOR            AgentCommunicationStyle = "EDUCATOR"
	AgentCommunicationStylePROACTIVECONSULTANT AgentCommunicationStyle = "PROACTIVE_CONSULTANT"
)

func (e *AgentCommunicationStyle) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentCommunicationStyle(s)
	case string:
		*e = AgentCommunicationStyle(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentCommunicationStyle: %T", src)
	}
	return nil
}

type NullAgentCommunicationStyle struct {
	AgentCommunicationStyle AgentCommunicationStyle `json:"agent_communication_style"`
	Valid                   bool                    `json:"valid"` // Valid is true if AgentCommunicationStyle is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentCommunicationStyle) Scan(value interface{}) error {
	if value == nil {
		ns.AgentCommunicationStyle, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentCommunicationStyle.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentCommunicationStyle) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentCommunicationStyle), nil
}

type AgentResponseLength string

const (
	AgentResponseLengthSHORT  AgentResponseLength = "SHORT"
	AgentResponseLengthMEDIUM AgentResponseLength = "MEDIUM"
	AgentResponseLengthLONG   AgentResponseLength = "LONG"
)

func (e *AgentResponseLength) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentResponseLength(s)
	case string:
		*e = AgentResponseLength(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentResponseLength: %T", src)
	}
	return nil
}

type NullAgentResponseLength struct {
	AgentResponseLength AgentResponseLength `json:"agent_response_length"`
	Valid               bool                `json:"valid"` // Valid is true if AgentResponseLength is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentResponseLength) Scan(value interface{}) error {
	if value == nil {
		ns.AgentResponseLength, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentResponseLength.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentResponseLength) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentResponseLength), nil
}

type AgentTone string

const (
	AgentToneFRIENDLY     AgentTone = "FRIENDLY"
	AgentTonePROFESSIONAL AgentTone = "PROFESSIONAL"
	AgentToneEXPLANATORY  AgentTone = "EXPLANATORY"
)

func (e *AgentTone) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AgentTone(s)
	case string:
		*e = AgentTone(s)
	default:
		return fmt.Errorf("unsupported scan type for AgentTone: %T", src)
	}
	return nil
}

type NullAgentTone struct {
	AgentTone AgentTone `json:"agent_tone"`
	Valid     bool      `json:"valid"` // Valid is true if AgentTone is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAgentTone) Scan(value interface{}) error {
	if value == nil {
		ns.AgentTone, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AgentTone.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAgentTone) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AgentTone), nil
}

type UpcomingChangesType string

const (
	UpcomingChangesTypeEmail          UpcomingChangesType = "email"
	UpcomingChangesTypePassword       UpcomingChangesType = "password"
	UpcomingChangesTypeForgotPassword UpcomingChangesType = "forgot-password"
)

func (e *UpcomingChangesType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UpcomingChangesType(s)
	case string:
		*e = UpcomingChangesType(s)
	default:
		return fmt.Errorf("unsupported scan type for UpcomingChangesType: %T", src)
	}
	return nil
}

type NullUpcomingChangesType struct {
	UpcomingChangesType UpcomingChangesType `json:"upcoming_changes_type"`
	Valid               bool                `json:"valid"` // Valid is true if UpcomingChangesType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUpcomingChangesType) Scan(value interface{}) error {
	if value == nil {
		ns.UpcomingChangesType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UpcomingChangesType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUpcomingChangesType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UpcomingChangesType), nil
}

type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
	UserRoleNew   UserRole = "new"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Agent struct {
	ID                 uuid.UUID               `json:"id"`
	Name               string                  `json:"name"`
	Description        *string                 `json:"description"`
	IsActive           bool                    `json:"is_active"`
	WebhookUri         string                  `json:"webhook_uri"`
	CreatedAt          time.Time               `json:"created_at"`
	UpdatedAt          time.Time               `json:"updated_at"`
	DeletedAt          *time.Time              `json:"deleted_at"`
	Tone               AgentTone               `json:"tone"`
	ResponseLength     AgentResponseLength     `json:"response_length"`
	CommunicationStyle AgentCommunicationStyle `json:"communication_style"`
}

type AgentKnowledge struct {
	ID           uuid.UUID  `json:"id"`
	IsActiveProd bool       `json:"is_active_prod"`
	IsActiveDev  bool       `json:"is_active_dev"`
	AgentID      uuid.UUID  `json:"agent_id"`
	KnowledgeID  uuid.UUID  `json:"knowledge_id"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	DeletedAt    *time.Time `json:"deleted_at"`
}

type AgentKnowledgesView struct {
	ID           uuid.UUID `json:"id"`
	AgentID      uuid.UUID `json:"agent_id"`
	KnowledgeID  uuid.UUID `json:"knowledge_id"`
	IsActiveProd bool      `json:"is_active_prod"`
	IsActiveDev  bool      `json:"is_active_dev"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type AgentsView struct {
	ID                 uuid.UUID               `json:"id"`
	Name               string                  `json:"name"`
	Description        *string                 `json:"description"`
	IsActive           bool                    `json:"is_active"`
	WebhookUri         string                  `json:"webhook_uri"`
	Tone               AgentTone               `json:"tone"`
	ResponseLength     AgentResponseLength     `json:"response_length"`
	CommunicationStyle AgentCommunicationStyle `json:"communication_style"`
	CreatedAt          time.Time               `json:"created_at"`
	UpdatedAt          time.Time               `json:"updated_at"`
}

type ApiKey struct {
	ID        uuid.UUID  `json:"id"`
	Name      string     `json:"name"`
	Token     string     `json:"token"`
	CreatedAt time.Time  `json:"created_at"`
	RevokedAt *time.Time `json:"revoked_at"`
}

type ApiKeysView struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
}

type Knowledge struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	SourceType  string     `json:"source_type"`
	SourceUri   *string    `json:"source_uri"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
}

type KnowledgesView struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	SourceType  string    `json:"source_type"`
	SourceUri   *string   `json:"source_uri"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Mcp struct {
	ID          uuid.UUID  `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	Uri         string     `json:"uri"`
	AgentID     uuid.UUID  `json:"agent_id"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
}

type McpTool struct {
	ID          uuid.UUID       `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	TargetUri   string          `json:"target_uri"`
	McpID       uuid.UUID       `json:"mcp_id"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
	DeletedAt   *time.Time      `json:"deleted_at"`
	InputSchema json.RawMessage `json:"input_schema"`
}

type McpToolsView struct {
	ID          uuid.UUID       `json:"id"`
	McpID       uuid.UUID       `json:"mcp_id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	TargetUri   string          `json:"target_uri"`
	InputSchema json.RawMessage `json:"input_schema"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type McpsView struct {
	ID          uuid.UUID `json:"id"`
	AgentID     uuid.UUID `json:"agent_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Uri         string    `json:"uri"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type UpcomingChange struct {
	ID            uuid.UUID           `json:"id"`
	Token         string              `json:"token"`
	Type          UpcomingChangesType `json:"type"`
	UpcomingValue *string             `json:"upcoming_value"`
	UserID        uuid.UUID           `json:"user_id"`
	CreatedAt     time.Time           `json:"created_at"`
	ExpiredAt     time.Time           `json:"expired_at"`
	RevokedAt     *time.Time          `json:"revoked_at"`
}

type User struct {
	ID             uuid.UUID  `json:"id"`
	Name           string     `json:"name"`
	Username       string     `json:"username"`
	Email          string     `json:"email"`
	Role           UserRole   `json:"role"`
	HashedPassword string     `json:"hashed_password"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
	DeletedAt      *time.Time `json:"deleted_at"`
}

type UsersView struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Role      UserRole  `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
