// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orchestrators.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countOrchestrators = `-- name: CountOrchestrators :one
SELECT COUNT(*) FROM orchestrators_view ov
WHERE (
    $1::text IS NULL
    OR ov.name ILIKE '%' || $1::text || '%'
    OR ov.description ILIKE '%' || $1::text || '%'
)
AND (
    $2::bool IS NULL
    OR ov.is_active = $2::bool
)
`

type CountOrchestratorsParams struct {
	Search   *string `json:"search"`
	IsActive *bool   `json:"is_active"`
}

func (q *Queries) CountOrchestrators(ctx context.Context, arg CountOrchestratorsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrchestrators, arg.Search, arg.IsActive)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertOrchestrator = `-- name: InsertOrchestrator :one
INSERT INTO orchestrators (name, description, is_active, orchestrator_agent_id, routing_guide, persona, guardrail, webhook_uri, webhook_input_field, webhook_output_field, webhook_body_fields, webhook_header_fields, webhook_stream_enabled, persona_enabled, guardrail_enabled)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
RETURNING
    id, name, description, is_active, orchestrator_agent_id, routing_guide, persona, guardrail, image, webhook_uri, webhook_input_field, webhook_output_field, webhook_body_fields, webhook_header_fields, webhook_stream_enabled, persona_enabled, guardrail_enabled, created_at, updated_at
`

type InsertOrchestratorParams struct {
	Name                 string          `json:"name"`
	Description          *string         `json:"description"`
	IsActive             bool            `json:"is_active"`
	OrchestratorAgentID  string          `json:"orchestrator_agent_id"`
	RoutingGuide         string          `json:"routing_guide"`
	Persona              string          `json:"persona"`
	Guardrail            string          `json:"guardrail"`
	WebhookUri           string          `json:"webhook_uri"`
	WebhookInputField    string          `json:"webhook_input_field"`
	WebhookOutputField   string          `json:"webhook_output_field"`
	WebhookBodyFields    json.RawMessage `json:"webhook_body_fields"`
	WebhookHeaderFields  json.RawMessage `json:"webhook_header_fields"`
	WebhookStreamEnabled bool            `json:"webhook_stream_enabled"`
	PersonaEnabled       bool            `json:"persona_enabled"`
	GuardrailEnabled     bool            `json:"guardrail_enabled"`
}

type InsertOrchestratorRow struct {
	ID                   uuid.UUID       `json:"id"`
	Name                 string          `json:"name"`
	Description          *string         `json:"description"`
	IsActive             bool            `json:"is_active"`
	OrchestratorAgentID  string          `json:"orchestrator_agent_id"`
	RoutingGuide         string          `json:"routing_guide"`
	Persona              string          `json:"persona"`
	Guardrail            string          `json:"guardrail"`
	Image                *string         `json:"image"`
	WebhookUri           string          `json:"webhook_uri"`
	WebhookInputField    string          `json:"webhook_input_field"`
	WebhookOutputField   string          `json:"webhook_output_field"`
	WebhookBodyFields    json.RawMessage `json:"webhook_body_fields"`
	WebhookHeaderFields  json.RawMessage `json:"webhook_header_fields"`
	WebhookStreamEnabled bool            `json:"webhook_stream_enabled"`
	PersonaEnabled       bool            `json:"persona_enabled"`
	GuardrailEnabled     bool            `json:"guardrail_enabled"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
}

func (q *Queries) InsertOrchestrator(ctx context.Context, arg InsertOrchestratorParams) (InsertOrchestratorRow, error) {
	row := q.db.QueryRow(ctx, insertOrchestrator,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.OrchestratorAgentID,
		arg.RoutingGuide,
		arg.Persona,
		arg.Guardrail,
		arg.WebhookUri,
		arg.WebhookInputField,
		arg.WebhookOutputField,
		arg.WebhookBodyFields,
		arg.WebhookHeaderFields,
		arg.WebhookStreamEnabled,
		arg.PersonaEnabled,
		arg.GuardrailEnabled,
	)
	var i InsertOrchestratorRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.OrchestratorAgentID,
		&i.RoutingGuide,
		&i.Persona,
		&i.Guardrail,
		&i.Image,
		&i.WebhookUri,
		&i.WebhookInputField,
		&i.WebhookOutputField,
		&i.WebhookBodyFields,
		&i.WebhookHeaderFields,
		&i.WebhookStreamEnabled,
		&i.PersonaEnabled,
		&i.GuardrailEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrchestratorAgent = `-- name: InsertOrchestratorAgent :one
INSERT INTO orchestrator_agents (orchestrator_id, agent_id, tool_name, description)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id, orchestrator_id, agent_id, tool_name, description, created_at, updated_at
`

type InsertOrchestratorAgentParams struct {
	OrchestratorID uuid.UUID `json:"orchestrator_id"`
	AgentID        uuid.UUID `json:"agent_id"`
	ToolName       string    `json:"tool_name"`
	Description    string    `json:"description"`
}

type InsertOrchestratorAgentRow struct {
	ID             uuid.UUID `json:"id"`
	OrchestratorID uuid.UUID `json:"orchestrator_id"`
	AgentID        uuid.UUID `json:"agent_id"`
	ToolName       string    `json:"tool_name"`
	Description    string    `json:"description"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) InsertOrchestratorAgent(ctx context.Context, arg InsertOrchestratorAgentParams) (InsertOrchestratorAgentRow, error) {
	row := q.db.QueryRow(ctx, insertOrchestratorAgent,
		arg.OrchestratorID,
		arg.AgentID,
		arg.ToolName,
		arg.Description,
	)
	var i InsertOrchestratorAgentRow
	err := row.Scan(
		&i.ID,
		&i.OrchestratorID,
		&i.AgentID,
		&i.ToolName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectOrchestratorAgents = `-- name: SelectOrchestratorAgents :many
SELECT
    oav.id,
    oav.orchestrator_id,
    oav.agent_id,
    oav.tool_name,
    oav.description,
    av.name AS agent_name,
    av.template_id AS endpoint,
    av.can_act,
    av.image AS agent_image
FROM orchestrator_agents_view oav
JOIN agents_view av ON av.id = oav.agent_id
WHERE oav.orchestrator_id = $1
ORDER BY oav.created_at ASC
`

type SelectOrchestratorAgentsRow struct {
	ID             uuid.UUID `json:"id"`
	OrchestratorID uuid.UUID `json:"orchestrator_id"`
	AgentID        uuid.UUID `json:"agent_id"`
	ToolName       string    `json:"tool_name"`
	Description    string    `json:"description"`
	AgentName      string    `json:"agent_name"`
	Endpoint       string    `json:"endpoint"`
	CanAct         bool      `json:"can_act"`
	AgentImage     *string   `json:"agent_image"`
}

// Per-agent mapping joined to the agent row so callers get the derived fields
// (endpoint == agent.template_id, can_act) without us storing them redundantly.
func (q *Queries) SelectOrchestratorAgents(ctx context.Context, orchestratorID uuid.UUID) ([]SelectOrchestratorAgentsRow, error) {
	rows, err := q.db.Query(ctx, selectOrchestratorAgents, orchestratorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectOrchestratorAgentsRow{}
	for rows.Next() {
		var i SelectOrchestratorAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrchestratorID,
			&i.AgentID,
			&i.ToolName,
			&i.Description,
			&i.AgentName,
			&i.Endpoint,
			&i.CanAct,
			&i.AgentImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectOrchestratorById = `-- name: SelectOrchestratorById :one
SELECT ov.id, ov.name, ov.description, ov.is_active, ov.orchestrator_agent_id, ov.routing_guide, ov.persona, ov.guardrail, ov.created_at, ov.updated_at, ov.image, ov.webhook_uri, ov.webhook_input_field, ov.webhook_output_field, ov.webhook_body_fields, ov.webhook_header_fields, ov.webhook_stream_enabled, ov.persona_enabled, ov.guardrail_enabled FROM orchestrators_view ov
WHERE ov.id = $1
LIMIT 1
`

func (q *Queries) SelectOrchestratorById(ctx context.Context, id uuid.UUID) (OrchestratorsView, error) {
	row := q.db.QueryRow(ctx, selectOrchestratorById, id)
	var i OrchestratorsView
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.OrchestratorAgentID,
		&i.RoutingGuide,
		&i.Persona,
		&i.Guardrail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Image,
		&i.WebhookUri,
		&i.WebhookInputField,
		&i.WebhookOutputField,
		&i.WebhookBodyFields,
		&i.WebhookHeaderFields,
		&i.WebhookStreamEnabled,
		&i.PersonaEnabled,
		&i.GuardrailEnabled,
	)
	return i, err
}

const selectOrchestrators = `-- name: SelectOrchestrators :many
SELECT
    ov.id, ov.name, ov.description, ov.is_active, ov.orchestrator_agent_id, ov.routing_guide, ov.persona, ov.guardrail, ov.created_at, ov.updated_at, ov.image, ov.webhook_uri, ov.webhook_input_field, ov.webhook_output_field, ov.webhook_body_fields, ov.webhook_header_fields, ov.webhook_stream_enabled, ov.persona_enabled, ov.guardrail_enabled,
    COALESCE(oa.agents_count, 0) AS agents_count
FROM orchestrators_view ov
LEFT JOIN (
    SELECT
        orchestrator_id,
        COUNT(*) AS agents_count
    FROM orchestrator_agents_view
    GROUP BY orchestrator_id
) oa ON oa.orchestrator_id = ov.id
WHERE (
    $1::text IS NULL
    OR ov.name ILIKE '%' || $1::text || '%'
    OR ov.description ILIKE '%' || $1::text || '%'
)
AND (
    $2::bool IS NULL
    OR ov.is_active = $2::bool
)
ORDER BY
    CASE
        WHEN $3::text = 'is_active_asc' THEN ov.is_active
    END DESC,
    CASE
        WHEN $3::text = 'is_active_desc' THEN ov.is_active
    END ASC,
    CASE WHEN $3::text = 'name_asc' THEN ov.name END ASC,
    CASE WHEN $3::text = 'name_desc' THEN ov.name END DESC,
    CASE
        WHEN $3::text = 'created_asc' THEN ov.created_at
    END ASC,
    CASE
        WHEN $3::text = 'created_desc' THEN ov.created_at
    END DESC,
    CASE
        WHEN $3::text = 'modified_asc' THEN ov.updated_at
    END ASC,
    CASE
        WHEN $3::text = 'modified_desc' THEN ov.updated_at
    END DESC,
    ov.created_at DESC
LIMIT $5 OFFSET $4
`

type SelectOrchestratorsParams struct {
	Search   *string `json:"search"`
	IsActive *bool   `json:"is_active"`
	Sort     *string `json:"sort"`
	Offset   int32   `json:"offset"`
	Limit    int32   `json:"limit"`
}

type SelectOrchestratorsRow struct {
	ID                   uuid.UUID       `json:"id"`
	Name                 string          `json:"name"`
	Description          *string         `json:"description"`
	IsActive             bool            `json:"is_active"`
	OrchestratorAgentID  string          `json:"orchestrator_agent_id"`
	RoutingGuide         string          `json:"routing_guide"`
	Persona              string          `json:"persona"`
	Guardrail            string          `json:"guardrail"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
	Image                *string         `json:"image"`
	WebhookUri           string          `json:"webhook_uri"`
	WebhookInputField    string          `json:"webhook_input_field"`
	WebhookOutputField   string          `json:"webhook_output_field"`
	WebhookBodyFields    json.RawMessage `json:"webhook_body_fields"`
	WebhookHeaderFields  json.RawMessage `json:"webhook_header_fields"`
	WebhookStreamEnabled bool            `json:"webhook_stream_enabled"`
	PersonaEnabled       bool            `json:"persona_enabled"`
	GuardrailEnabled     bool            `json:"guardrail_enabled"`
	AgentsCount          int64           `json:"agents_count"`
}

func (q *Queries) SelectOrchestrators(ctx context.Context, arg SelectOrchestratorsParams) ([]SelectOrchestratorsRow, error) {
	rows, err := q.db.Query(ctx, selectOrchestrators,
		arg.Search,
		arg.IsActive,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectOrchestratorsRow{}
	for rows.Next() {
		var i SelectOrchestratorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.OrchestratorAgentID,
			&i.RoutingGuide,
			&i.Persona,
			&i.Guardrail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Image,
			&i.WebhookUri,
			&i.WebhookInputField,
			&i.WebhookOutputField,
			&i.WebhookBodyFields,
			&i.WebhookHeaderFields,
			&i.WebhookStreamEnabled,
			&i.PersonaEnabled,
			&i.GuardrailEnabled,
			&i.AgentsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOrchestrator = `-- name: SoftDeleteOrchestrator :execrows
UPDATE orchestrators
SET deleted_at = NOW()
WHERE
    deleted_at IS NULL
    AND id = $1
`

func (q *Queries) SoftDeleteOrchestrator(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteOrchestrator, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOrchestrator = `-- name: UpdateOrchestrator :one
UPDATE orchestrators
SET
    name = $1,
    description = $2,
    is_active = $3,
    -- Omitted (NULL) keeps the stored text; an empty string clears it. These
    -- are generated upstream at create time and are expensive to lose.
    routing_guide = COALESCE($4, routing_guide),
    persona = COALESCE($5, persona),
    guardrail = COALESCE($6, guardrail),
    image = $7,
    webhook_uri = $8,
    webhook_input_field = $9,
    webhook_output_field = $10,
    -- NULL means "field omitted by the caller": keep what is stored. An empty
    -- JSON array clears it. Stops partial clients from wiping stored auth.
    webhook_body_fields = COALESCE($11, webhook_body_fields),
    webhook_header_fields = COALESCE($12, webhook_header_fields),
    webhook_stream_enabled = COALESCE($13, webhook_stream_enabled),
    persona_enabled = COALESCE($14, persona_enabled),
    guardrail_enabled = COALESCE($15, guardrail_enabled),
    updated_at = NOW()
WHERE
    deleted_at IS NULL
    AND id = $16
RETURNING
    id, name, description, is_active, orchestrator_agent_id, routing_guide, persona, guardrail, image, webhook_uri, webhook_input_field, webhook_output_field, webhook_body_fields, webhook_header_fields, webhook_stream_enabled, persona_enabled, guardrail_enabled, created_at, updated_at
`

type UpdateOrchestratorParams struct {
	Name                 string          `json:"name"`
	Description          *string         `json:"description"`
	IsActive             bool            `json:"is_active"`
	RoutingGuide         *string         `json:"routing_guide"`
	Persona              *string         `json:"persona"`
	Guardrail            *string         `json:"guardrail"`
	Image                *string         `json:"image"`
	WebhookUri           string          `json:"webhook_uri"`
	WebhookInputField    string          `json:"webhook_input_field"`
	WebhookOutputField   string          `json:"webhook_output_field"`
	WebhookBodyFields    json.RawMessage `json:"webhook_body_fields"`
	WebhookHeaderFields  json.RawMessage `json:"webhook_header_fields"`
	WebhookStreamEnabled *bool           `json:"webhook_stream_enabled"`
	PersonaEnabled       *bool           `json:"persona_enabled"`
	GuardrailEnabled     *bool           `json:"guardrail_enabled"`
	ID                   uuid.UUID       `json:"id"`
}

type UpdateOrchestratorRow struct {
	ID                   uuid.UUID       `json:"id"`
	Name                 string          `json:"name"`
	Description          *string         `json:"description"`
	IsActive             bool            `json:"is_active"`
	OrchestratorAgentID  string          `json:"orchestrator_agent_id"`
	RoutingGuide         string          `json:"routing_guide"`
	Persona              string          `json:"persona"`
	Guardrail            string          `json:"guardrail"`
	Image                *string         `json:"image"`
	WebhookUri           string          `json:"webhook_uri"`
	WebhookInputField    string          `json:"webhook_input_field"`
	WebhookOutputField   string          `json:"webhook_output_field"`
	WebhookBodyFields    json.RawMessage `json:"webhook_body_fields"`
	WebhookHeaderFields  json.RawMessage `json:"webhook_header_fields"`
	WebhookStreamEnabled bool            `json:"webhook_stream_enabled"`
	PersonaEnabled       bool            `json:"persona_enabled"`
	GuardrailEnabled     bool            `json:"guardrail_enabled"`
	CreatedAt            time.Time       `json:"created_at"`
	UpdatedAt            time.Time       `json:"updated_at"`
}

func (q *Queries) UpdateOrchestrator(ctx context.Context, arg UpdateOrchestratorParams) (UpdateOrchestratorRow, error) {
	row := q.db.QueryRow(ctx, updateOrchestrator,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.RoutingGuide,
		arg.Persona,
		arg.Guardrail,
		arg.Image,
		arg.WebhookUri,
		arg.WebhookInputField,
		arg.WebhookOutputField,
		arg.WebhookBodyFields,
		arg.WebhookHeaderFields,
		arg.WebhookStreamEnabled,
		arg.PersonaEnabled,
		arg.GuardrailEnabled,
		arg.ID,
	)
	var i UpdateOrchestratorRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.OrchestratorAgentID,
		&i.RoutingGuide,
		&i.Persona,
		&i.Guardrail,
		&i.Image,
		&i.WebhookUri,
		&i.WebhookInputField,
		&i.WebhookOutputField,
		&i.WebhookBodyFields,
		&i.WebhookHeaderFields,
		&i.WebhookStreamEnabled,
		&i.PersonaEnabled,
		&i.GuardrailEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
