// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pins.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deletePin = `-- name: DeletePin :execrows
DELETE FROM pins
WHERE
    user_id = $1
    AND entity_type = $2
    AND entity_id = $3
`

type DeletePinParams struct {
	UserID     uuid.UUID `json:"user_id"`
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) DeletePin(ctx context.Context, arg DeletePinParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePin, arg.UserID, arg.EntityType, arg.EntityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePinById = `-- name: DeletePinById :execrows
DELETE FROM pins
WHERE id = $1 AND user_id = $2
`

type DeletePinByIdParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePinById(ctx context.Context, arg DeletePinByIdParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePinById, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPin = `-- name: InsertPin :one
INSERT INTO pins (user_id, entity_type, entity_id, position)
VALUES (
    $1,
    $2,
    $3,
    COALESCE(
        (SELECT MAX(position) + 1 FROM pins WHERE user_id = $1),
        0
    )
)
ON CONFLICT (user_id, entity_type, entity_id)
DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING id, user_id, entity_type, entity_id, position, created_at
`

type InsertPinParams struct {
	UserID     uuid.UUID `json:"user_id"`
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

// Idempotent: re-pinning the same entity is a no-op that returns the existing
// pin. Position is appended at the end of the user's current list.
func (q *Queries) InsertPin(ctx context.Context, arg InsertPinParams) (Pin, error) {
	row := q.db.QueryRow(ctx, insertPin, arg.UserID, arg.EntityType, arg.EntityID)
	var i Pin
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntityType,
		&i.EntityID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const selectPinnedEntityIds = `-- name: SelectPinnedEntityIds :many
SELECT entity_type, entity_id
FROM pins
WHERE user_id = $1
`

type SelectPinnedEntityIdsRow struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

// Lightweight lookup for the frontend to know which entities are pinned (used to
// toggle the pin button state) without resolving labels.
func (q *Queries) SelectPinnedEntityIds(ctx context.Context, userID uuid.UUID) ([]SelectPinnedEntityIdsRow, error) {
	rows, err := q.db.Query(ctx, selectPinnedEntityIds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectPinnedEntityIdsRow{}
	for rows.Next() {
		var i SelectPinnedEntityIdsRow
		if err := rows.Scan(&i.EntityType, &i.EntityID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectResolvedPins = `-- name: SelectResolvedPins :many
SELECT
    p.id,
    p.entity_type,
    p.entity_id,
    p.position,
    p.created_at,
    COALESCE(d.name, a.name, o.name, ca.name) AS label,
    COALESCE(a.image, o.image, ca.image) AS image,
    (
        d.id IS NOT NULL
        OR a.id IS NOT NULL
        OR o.id IS NOT NULL
        OR c.id IS NOT NULL
    )::bool AS resolved
FROM pins p
LEFT JOIN dashboards_view d
    ON p.entity_type = 'dashboard' AND d.id = p.entity_id
LEFT JOIN agents_view a
    ON p.entity_type = 'agent' AND a.id = p.entity_id
LEFT JOIN orchestrators_view o
    ON p.entity_type = 'orchestrator' AND o.id = p.entity_id
LEFT JOIN conversations_view c
    ON p.entity_type = 'chat' AND c.id = p.entity_id
LEFT JOIN agents_view ca
    ON ca.id = c.agent_id
WHERE p.user_id = $1
ORDER BY p.position ASC, p.created_at ASC
`

type SelectResolvedPinsRow struct {
	ID         uuid.UUID `json:"id"`
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	Position   int32     `json:"position"`
	CreatedAt  time.Time `json:"created_at"`
	Label      string    `json:"label"`
	Image      *string   `json:"image"`
	Resolved   bool      `json:"resolved"`
}

// The sidebar payload: each pin resolved to its current label + image via a
// LEFT JOIN per entity type. Chat pins borrow the agent's name/image. Rows whose
// target was deleted resolve to a NULL label and are dropped by the handler.
func (q *Queries) SelectResolvedPins(ctx context.Context, userID uuid.UUID) ([]SelectResolvedPinsRow, error) {
	rows, err := q.db.Query(ctx, selectResolvedPins, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectResolvedPinsRow{}
	for rows.Next() {
		var i SelectResolvedPinsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Position,
			&i.CreatedAt,
			&i.Label,
			&i.Image,
			&i.Resolved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePinPosition = `-- name: UpdatePinPosition :execrows
UPDATE pins
SET position = $1
WHERE id = $2 AND user_id = $3
`

type UpdatePinPositionParams struct {
	Position int32     `json:"position"`
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdatePinPosition(ctx context.Context, arg UpdatePinPositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePinPosition, arg.Position, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
