// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptMember(ctx context.Context, id uuid.UUID) (AcceptMemberRow, error)
	CountAgentKnowledgesByAgentId(ctx context.Context, agentID uuid.UUID) (int64, error)
	CountAgents(ctx context.Context) (int64, error)
	CountApiKeys(ctx context.Context) (int64, error)
	CountKnowledges(ctx context.Context, sourceType *string) (int64, error)
	CountMcpToolsByMcpId(ctx context.Context, mcpID uuid.UUID) (int64, error)
	CountMcps(ctx context.Context) (int64, error)
	CountMembers(ctx context.Context, role *string) (int64, error)
	InsertAgent(ctx context.Context, arg InsertAgentParams) (InsertAgentRow, error)
	InsertAgentKnowledge(ctx context.Context, arg InsertAgentKnowledgeParams) (InsertAgentKnowledgeRow, error)
	InsertApiKey(ctx context.Context, arg InsertApiKeyParams) (InsertApiKeyRow, error)
	InsertKnowledge(ctx context.Context, arg InsertKnowledgeParams) (InsertKnowledgeRow, error)
	InsertMcp(ctx context.Context, arg InsertMcpParams) (InsertMcpRow, error)
	InsertMcpTool(ctx context.Context, arg InsertMcpToolParams) (InsertMcpToolRow, error)
	InsertUpcomingChange(ctx context.Context, arg InsertUpcomingChangeParams) (UpcomingChange, error)
	InsertUserRegister(ctx context.Context, arg InsertUserRegisterParams) (InsertUserRegisterRow, error)
	RevokeApiKey(ctx context.Context, id uuid.UUID) (int64, error)
	RevokeUpcomingChangeByID(ctx context.Context, id uuid.UUID) error
	SelectAgentById(ctx context.Context, id uuid.UUID) (SelectAgentByIdRow, error)
	SelectAgentKnowledgesByAgentId(ctx context.Context, arg SelectAgentKnowledgesByAgentIdParams) ([]SelectAgentKnowledgesByAgentIdRow, error)
	SelectAgents(ctx context.Context, arg SelectAgentsParams) ([]SelectAgentsRow, error)
	SelectApiKeyByToken(ctx context.Context, token string) (ApiKeysView, error)
	SelectApiKeys(ctx context.Context, arg SelectApiKeysParams) ([]ApiKeysView, error)
	SelectKnowledgeById(ctx context.Context, id uuid.UUID) (KnowledgesView, error)
	SelectKnowledges(ctx context.Context, arg SelectKnowledgesParams) ([]KnowledgesView, error)
	SelectMcpById(ctx context.Context, id uuid.UUID) (McpsView, error)
	SelectMcpToolsByMcpId(ctx context.Context, mcpID uuid.UUID) ([]McpToolsView, error)
	SelectMcps(ctx context.Context, arg SelectMcpsParams) ([]McpsView, error)
	SelectMembers(ctx context.Context, arg SelectMembersParams) ([]UsersView, error)
	SelectUpcomingChangeByToken(ctx context.Context, token string) (UpcomingChange, error)
	SelectUserById(ctx context.Context, id uuid.UUID) (UsersView, error)
	SelectUserByIdWithPassword(ctx context.Context, id uuid.UUID) (SelectUserByIdWithPasswordRow, error)
	SelectUserByLoginIdWithPassword(ctx context.Context, loginID string) (SelectUserByLoginIdWithPasswordRow, error)
	SoftDeleteAgent(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteAgentKnowledge(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteKnowledge(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteMcp(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteMcpToolsByMcpId(ctx context.Context, mcpID uuid.UUID) (int64, error)
	SoftDeleteMember(ctx context.Context, id uuid.UUID) (int64, error)
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) (UpdateAgentRow, error)
	UpdateAgentKnowledge(ctx context.Context, arg UpdateAgentKnowledgeParams) (UpdateAgentKnowledgeRow, error)
	UpdateAgentPersona(ctx context.Context, arg UpdateAgentPersonaParams) (UpdateAgentPersonaRow, error)
	UpdateKnowledge(ctx context.Context, arg UpdateKnowledgeParams) (UpdateKnowledgeRow, error)
	UpdateMcp(ctx context.Context, arg UpdateMcpParams) (UpdateMcpRow, error)
	UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) (UpdateMemberStatusRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
