// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteAgent(ctx context.Context, id uuid.UUID) (int64, error)
	InsertAgent(ctx context.Context, arg InsertAgentParams) (Agent, error)
	SelectAgentById(ctx context.Context, id uuid.UUID) (Agent, error)
	SelectAgents(ctx context.Context, arg SelectAgentsParams) ([]Agent, error)
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error)
}

var _ Querier = (*Queries)(nil)
