// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptMember(ctx context.Context, id uuid.UUID) (AcceptMemberRow, error)
	// Marks a conversation ended. end_reason arrives lowercase on the wire
	// (e.g. "timed_out"); upper() maps it onto the CONVERSATION_END_REASON enum.
	// Guarded by is_active so a replayed/duplicate end event is a no-op.
	CloseConversation(ctx context.Context, arg CloseConversationParams) error
	CountAgentKnowledgesByAgentId(ctx context.Context, agentID uuid.UUID) (int64, error)
	CountAgents(ctx context.Context, arg CountAgentsParams) (int64, error)
	CountAgentsByKnowledgeId(ctx context.Context) (int64, error)
	CountAgentsByMcpId(ctx context.Context) (int64, error)
	CountAllKnowledges(ctx context.Context, search *string) (int64, error)
	CountApiKeys(ctx context.Context) (int64, error)
	CountConversations(ctx context.Context) (int64, error)
	CountKnowledges(ctx context.Context, arg CountKnowledgesParams) (int64, error)
	CountKnowledgesByAgentId(ctx context.Context, arg CountKnowledgesByAgentIdParams) (int64, error)
	CountMcpToolsByMcpId(ctx context.Context, mcpID uuid.UUID) (int64, error)
	CountMcps(ctx context.Context, arg CountMcpsParams) (int64, error)
	CountMcpsByAgentId(ctx context.Context, arg CountMcpsByAgentIdParams) (int64, error)
	CountMembers(ctx context.Context, role *string) (int64, error)
	CountOrchestrators(ctx context.Context, arg CountOrchestratorsParams) (int64, error)
	DeleteAgentTags(ctx context.Context, agentID uuid.UUID) error
	DeleteConversation(ctx context.Context, id uuid.UUID) error
	DeleteDashboardImport(ctx context.Context, arg DeleteDashboardImportParams) (int64, error)
	DeleteKnowledgeTags(ctx context.Context, knowledgeID uuid.UUID) error
	DeleteMcpTags(ctx context.Context, mcpID uuid.UUID) error
	DeleteMessagesByConversation(ctx context.Context, conversationID uuid.UUID) error
	DeletePin(ctx context.Context, arg DeletePinParams) (int64, error)
	DeletePinById(ctx context.Context, arg DeletePinByIdParams) (int64, error)
	GetGlobalConfig(ctx context.Context) (GlobalConfig, error)
	InsertAgent(ctx context.Context, arg InsertAgentParams) (InsertAgentRow, error)
	InsertAgentKnowledge(ctx context.Context, arg InsertAgentKnowledgeParams) (InsertAgentKnowledgeRow, error)
	InsertAgentMcp(ctx context.Context, arg InsertAgentMcpParams) (InsertAgentMcpRow, error)
	InsertAgentTag(ctx context.Context, arg InsertAgentTagParams) error
	InsertApiKey(ctx context.Context, arg InsertApiKeyParams) (InsertApiKeyRow, error)
	InsertDashboard(ctx context.Context, arg InsertDashboardParams) (InsertDashboardRow, error)
	// Idempotent import: ON CONFLICT means re-importing is a no-op.
	InsertDashboardImport(ctx context.Context, arg InsertDashboardImportParams) (int64, error)
	InsertKnowledge(ctx context.Context, arg InsertKnowledgeParams) (InsertKnowledgeRow, error)
	InsertKnowledgeTag(ctx context.Context, arg InsertKnowledgeTagParams) error
	InsertMcp(ctx context.Context, arg InsertMcpParams) (InsertMcpRow, error)
	InsertMcpTag(ctx context.Context, arg InsertMcpTagParams) error
	InsertMcpTool(ctx context.Context, arg InsertMcpToolParams) (InsertMcpToolRow, error)
	InsertMessage(ctx context.Context, arg InsertMessageParams) error
	InsertOrchestrator(ctx context.Context, arg InsertOrchestratorParams) (InsertOrchestratorRow, error)
	InsertOrchestratorAgent(ctx context.Context, arg InsertOrchestratorAgentParams) (InsertOrchestratorAgentRow, error)
	// Idempotent: re-pinning the same entity is a no-op that returns the existing
	// pin. Position is appended at the end of the user's current list.
	InsertPin(ctx context.Context, arg InsertPinParams) (Pin, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (InsertRefreshTokenRow, error)
	InsertUpcomingChange(ctx context.Context, arg InsertUpcomingChangeParams) (UpcomingChange, error)
	// Creates a passwordless PENDING user for the email-invite flow. Username/name
	// default to the email until the invitee sets their own on accept.
	InsertUserInvite(ctx context.Context, email string) (InsertUserInviteRow, error)
	InsertUserRegister(ctx context.Context, arg InsertUserRegisterParams) (InsertUserRegisterRow, error)
	ListMessagesByConversation(ctx context.Context, conversationID uuid.UUID) ([]Message, error)
	// Admin-gated at the handler; records who published and when.
	PublishDashboard(ctx context.Context, arg PublishDashboardParams) (PublishDashboardRow, error)
	// Kill every active session for a user (logout-all / on status change).
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeApiKey(ctx context.Context, id uuid.UUID) (int64, error)
	RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) error
	RevokeRefreshTokenByID(ctx context.Context, id uuid.UUID) error
	RevokeUpcomingChangeByID(ctx context.Context, id uuid.UUID) error
	// Returns the session together with the CURRENT user role/deleted state, so the
	// refresh handler re-checks the live user on every refresh (a suspended or
	// soft-deleted user's session stops refreshing immediately).
	SelectActiveRefreshToken(ctx context.Context, tokenHash string) (SelectActiveRefreshTokenRow, error)
	SelectAgentById(ctx context.Context, id uuid.UUID) (SelectAgentByIdRow, error)
	SelectAgentKnowledgeByPair(ctx context.Context, arg SelectAgentKnowledgeByPairParams) (SelectAgentKnowledgeByPairRow, error)
	SelectAgentKnowledgesByAgentId(ctx context.Context, arg SelectAgentKnowledgesByAgentIdParams) ([]SelectAgentKnowledgesByAgentIdRow, error)
	SelectAgents(ctx context.Context, arg SelectAgentsParams) ([]SelectAgentsRow, error)
	SelectAgentsByKnowledgeId(ctx context.Context, arg SelectAgentsByKnowledgeIdParams) ([]SelectAgentsByKnowledgeIdRow, error)
	SelectAgentsByMcpId(ctx context.Context, arg SelectAgentsByMcpIdParams) ([]SelectAgentsByMcpIdRow, error)
	// Auth lookup: rejects expired keys (NULL expires_at = never expires).
	SelectApiKeyByToken(ctx context.Context, token string) (ApiKeysView, error)
	SelectApiKeys(ctx context.Context, arg SelectApiKeysParams) ([]ApiKeysView, error)
	SelectConversationById(ctx context.Context, id uuid.UUID) (SelectConversationByIdRow, error)
	SelectConversations(ctx context.Context, arg SelectConversationsParams) ([]SelectConversationsRow, error)
	SelectDashboardById(ctx context.Context, id uuid.UUID) (DashboardsView, error)
	SelectDashboardImport(ctx context.Context, arg SelectDashboardImportParams) (DashboardImport, error)
	SelectDropdownAgents(ctx context.Context, arg SelectDropdownAgentsParams) ([]SelectDropdownAgentsRow, error)
	SelectKnowledgeById(ctx context.Context, id uuid.UUID) (SelectKnowledgeByIdRow, error)
	SelectKnowledges(ctx context.Context, arg SelectKnowledgesParams) ([]SelectKnowledgesRow, error)
	SelectKnowledgesByAgentId(ctx context.Context, arg SelectKnowledgesByAgentIdParams) ([]SelectKnowledgesByAgentIdRow, error)
	SelectKnowledgesWithAgentStatus(ctx context.Context, arg SelectKnowledgesWithAgentStatusParams) ([]SelectKnowledgesWithAgentStatusRow, error)
	SelectMcpById(ctx context.Context, id uuid.UUID) (SelectMcpByIdRow, error)
	SelectMcpToolsByMcpId(ctx context.Context, mcpID uuid.UUID) ([]McpToolsView, error)
	SelectMcps(ctx context.Context, arg SelectMcpsParams) ([]SelectMcpsRow, error)
	SelectMcpsByAgentId(ctx context.Context, arg SelectMcpsByAgentIdParams) ([]SelectMcpsByAgentIdRow, error)
	SelectMcpsWithAgentStatus(ctx context.Context, arg SelectMcpsWithAgentStatusParams) ([]SelectMcpsWithAgentStatusRow, error)
	// invited_token: the active (non-revoked, non-expired) INVITE token, if any,
	// so the UI can surface the accept link for pending invites.
	SelectMembers(ctx context.Context, arg SelectMembersParams) ([]SelectMembersRow, error)
	// Everything the caller can see in their sidebar: dashboards they own PLUS
	// published dashboards they've imported. `is_owner` distinguishes edit rights;
	// `imported` flags the ones that came from someone else.
	SelectMyDashboards(ctx context.Context, userID uuid.UUID) ([]SelectMyDashboardsRow, error)
	// Per-agent mapping joined to the agent row so callers get the derived fields
	// (endpoint == agent.template_id, can_act) without us storing them redundantly.
	SelectOrchestratorAgents(ctx context.Context, orchestratorID uuid.UUID) ([]SelectOrchestratorAgentsRow, error)
	SelectOrchestratorById(ctx context.Context, id uuid.UUID) (OrchestratorsView, error)
	SelectOrchestrators(ctx context.Context, arg SelectOrchestratorsParams) ([]SelectOrchestratorsRow, error)
	// Lightweight lookup for the frontend to know which entities are pinned (used to
	// toggle the pin button state) without resolving labels.
	SelectPinnedEntityIds(ctx context.Context, userID uuid.UUID) ([]SelectPinnedEntityIdsRow, error)
	// The team catalog: all published dashboards, with a flag telling the caller
	// which ones they've already imported and whether they own it.
	SelectPublishedDashboards(ctx context.Context, userID uuid.UUID) ([]SelectPublishedDashboardsRow, error)
	// The sidebar payload: each pin resolved to its current label + image via a
	// LEFT JOIN per entity type. Chat pins borrow the agent's name/image. Rows whose
	// target was deleted resolve to a NULL label and are dropped by the handler.
	SelectResolvedPins(ctx context.Context, userID uuid.UUID) ([]SelectResolvedPinsRow, error)
	SelectTags(ctx context.Context) ([]SelectTagsRow, error)
	SelectUpcomingChangeByToken(ctx context.Context, token string) (UpcomingChange, error)
	SelectUserById(ctx context.Context, id uuid.UUID) (UsersView, error)
	SelectUserByIdWithPassword(ctx context.Context, id uuid.UUID) (SelectUserByIdWithPasswordRow, error)
	SelectUserByLoginIdWithPassword(ctx context.Context, loginID string) (SelectUserByLoginIdWithPasswordRow, error)
	// Invite accept: set the password and promote PENDING -> VIEWER in one step.
	SetPasswordAndActivate(ctx context.Context, arg SetPasswordAndActivateParams) (SetPasswordAndActivateRow, error)
	SoftDeleteAgent(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteAgentKnowledge(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteAgentKnowledgeByPair(ctx context.Context, arg SoftDeleteAgentKnowledgeByPairParams) (uuid.UUID, error)
	SoftDeleteAgentMcp(ctx context.Context, arg SoftDeleteAgentMcpParams) (int64, error)
	// Owner-scoped delete.
	SoftDeleteDashboard(ctx context.Context, arg SoftDeleteDashboardParams) (int64, error)
	SoftDeleteKnowledge(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteMcp(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteMcpToolsByMcpId(ctx context.Context, mcpID uuid.UUID) (int64, error)
	SoftDeleteMember(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteOrchestrator(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteTag(ctx context.Context, id uuid.UUID) (int64, error)
	TouchRefreshToken(ctx context.Context, id uuid.UUID) error
	UnpublishDashboard(ctx context.Context, id uuid.UUID) (UnpublishDashboardRow, error)
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) (UpdateAgentRow, error)
	UpdateAgentKnowledge(ctx context.Context, arg UpdateAgentKnowledgeParams) (UpdateAgentKnowledgeRow, error)
	UpdateAgentKnowledgeStatus(ctx context.Context, arg UpdateAgentKnowledgeStatusParams) (int64, error)
	UpdateAgentPersona(ctx context.Context, arg UpdateAgentPersonaParams) (UpdateAgentPersonaRow, error)
	UpdateApiKeyName(ctx context.Context, arg UpdateApiKeyNameParams) (UpdateApiKeyNameRow, error)
	// Owner-scoped: the WHERE clause enforces that only the owner's row is touched.
	UpdateDashboard(ctx context.Context, arg UpdateDashboardParams) (UpdateDashboardRow, error)
	UpdateGlobalConfig(ctx context.Context, arg UpdateGlobalConfigParams) (GlobalConfig, error)
	UpdateKnowledge(ctx context.Context, arg UpdateKnowledgeParams) (UpdateKnowledgeRow, error)
	UpdateMcp(ctx context.Context, arg UpdateMcpParams) (UpdateMcpRow, error)
	UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) (UpdateMemberStatusRow, error)
	UpdateOrchestrator(ctx context.Context, arg UpdateOrchestratorParams) (UpdateOrchestratorRow, error)
	UpdatePinPosition(ctx context.Context, arg UpdatePinPositionParams) (int64, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (UpdateTagRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpsertConversation(ctx context.Context, arg UpsertConversationParams) error
	// Insert a tag by name, or return the existing live one (case-insensitive).
	// ON CONFLICT targets the partial unique index on lower(name) WHERE deleted_at IS NULL.
	UpsertTagByName(ctx context.Context, arg UpsertTagByNameParams) (UpsertTagByNameRow, error)
}

var _ Querier = (*Queries)(nil)
