// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refreshTokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, user_agent, ip, expires_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, expires_at, created_at
`

type InsertRefreshTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	UserAgent string    `json:"user_agent"`
	Ip        string    `json:"ip"`
	ExpiresAt time.Time `json:"expires_at"`
}

type InsertRefreshTokenRow struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (InsertRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	var i InsertRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

// Kill every active session for a user (logout-all / on status change).
func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByHash, tokenHash)
	return err
}

const revokeRefreshTokenByID = `-- name: RevokeRefreshTokenByID :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByID, id)
	return err
}

const selectActiveRefreshToken = `-- name: SelectActiveRefreshToken :one
SELECT
    rt.id,
    rt.user_id,
    rt.expires_at,
    u.role,
    u.deleted_at
FROM refresh_tokens rt
JOIN users u ON u.id = rt.user_id
WHERE rt.token_hash = $1
    AND rt.revoked_at IS NULL
    AND rt.expires_at > now()
LIMIT 1
`

type SelectActiveRefreshTokenRow struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	ExpiresAt time.Time  `json:"expires_at"`
	Role      UserRole   `json:"role"`
	DeletedAt *time.Time `json:"deleted_at"`
}

// Returns the session together with the CURRENT user role/deleted state, so the
// refresh handler re-checks the live user on every refresh (a suspended or
// soft-deleted user's session stops refreshing immediately).
func (q *Queries) SelectActiveRefreshToken(ctx context.Context, tokenHash string) (SelectActiveRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, selectActiveRefreshToken, tokenHash)
	var i SelectActiveRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.Role,
		&i.DeletedAt,
	)
	return i, err
}

const touchRefreshToken = `-- name: TouchRefreshToken :exec
UPDATE refresh_tokens
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchRefreshToken, id)
	return err
}
