// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteAgentTags = `-- name: DeleteAgentTags :exec
DELETE FROM agent_tags WHERE agent_id = $1
`

func (q *Queries) DeleteAgentTags(ctx context.Context, agentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentTags, agentID)
	return err
}

const deleteKnowledgeTags = `-- name: DeleteKnowledgeTags :exec
DELETE FROM knowledge_tags WHERE knowledge_id = $1
`

func (q *Queries) DeleteKnowledgeTags(ctx context.Context, knowledgeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteKnowledgeTags, knowledgeID)
	return err
}

const deleteMcpTags = `-- name: DeleteMcpTags :exec
DELETE FROM mcp_tags WHERE mcp_id = $1
`

func (q *Queries) DeleteMcpTags(ctx context.Context, mcpID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMcpTags, mcpID)
	return err
}

const insertAgentTag = `-- name: InsertAgentTag :exec
INSERT INTO agent_tags (agent_id, tag_id)
VALUES ($1, $2)
ON CONFLICT (agent_id, tag_id) DO NOTHING
`

type InsertAgentTagParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	TagID   uuid.UUID `json:"tag_id"`
}

func (q *Queries) InsertAgentTag(ctx context.Context, arg InsertAgentTagParams) error {
	_, err := q.db.Exec(ctx, insertAgentTag, arg.AgentID, arg.TagID)
	return err
}

const insertKnowledgeTag = `-- name: InsertKnowledgeTag :exec
INSERT INTO knowledge_tags (knowledge_id, tag_id)
VALUES ($1, $2)
ON CONFLICT (knowledge_id, tag_id) DO NOTHING
`

type InsertKnowledgeTagParams struct {
	KnowledgeID uuid.UUID `json:"knowledge_id"`
	TagID       uuid.UUID `json:"tag_id"`
}

func (q *Queries) InsertKnowledgeTag(ctx context.Context, arg InsertKnowledgeTagParams) error {
	_, err := q.db.Exec(ctx, insertKnowledgeTag, arg.KnowledgeID, arg.TagID)
	return err
}

const insertMcpTag = `-- name: InsertMcpTag :exec
INSERT INTO mcp_tags (mcp_id, tag_id)
VALUES ($1, $2)
ON CONFLICT (mcp_id, tag_id) DO NOTHING
`

type InsertMcpTagParams struct {
	McpID uuid.UUID `json:"mcp_id"`
	TagID uuid.UUID `json:"tag_id"`
}

func (q *Queries) InsertMcpTag(ctx context.Context, arg InsertMcpTagParams) error {
	_, err := q.db.Exec(ctx, insertMcpTag, arg.McpID, arg.TagID)
	return err
}

const selectTags = `-- name: SelectTags :many
SELECT
    t.id, t.name, t.color, t.created_at, t.updated_at,
    (
        SELECT COUNT(*)
        FROM agent_tags at
        JOIN agents a ON a.id = at.agent_id AND a.deleted_at IS NULL
        WHERE at.tag_id = t.id
    ) AS agents_count,
    (
        SELECT COUNT(*)
        FROM mcp_tags mt
        JOIN mcps m ON m.id = mt.mcp_id AND m.deleted_at IS NULL
        WHERE mt.tag_id = t.id
    ) AS mcps_count,
    (
        SELECT COUNT(*)
        FROM knowledge_tags kt
        JOIN knowledges k ON k.id = kt.knowledge_id AND k.deleted_at IS NULL
        WHERE kt.tag_id = t.id
    ) AS knowledges_count
FROM tags_view t
ORDER BY t.name
`

type SelectTagsRow struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Color           string    `json:"color"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	AgentsCount     int64     `json:"agents_count"`
	McpsCount       int64     `json:"mcps_count"`
	KnowledgesCount int64     `json:"knowledges_count"`
}

func (q *Queries) SelectTags(ctx context.Context) ([]SelectTagsRow, error) {
	rows, err := q.db.Query(ctx, selectTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectTagsRow{}
	for rows.Next() {
		var i SelectTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AgentsCount,
			&i.McpsCount,
			&i.KnowledgesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTag = `-- name: SoftDeleteTag :execrows
UPDATE tags
SET deleted_at = NOW()
WHERE
    deleted_at IS NULL
    AND id = $1
`

func (q *Queries) SoftDeleteTag(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTag, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET
    name = $1,
    color = $2,
    updated_at = NOW()
WHERE
    deleted_at IS NULL
    AND id = $3
RETURNING id, name, color, created_at, updated_at
`

type UpdateTagParams struct {
	Name  string    `json:"name"`
	Color string    `json:"color"`
	ID    uuid.UUID `json:"id"`
}

type UpdateTagRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (UpdateTagRow, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.Name, arg.Color, arg.ID)
	var i UpdateTagRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTagByName = `-- name: UpsertTagByName :one
INSERT INTO tags (name, color)
VALUES ($1, $2)
ON CONFLICT (lower(name)) WHERE deleted_at IS NULL
DO UPDATE SET name = tags.name
RETURNING id, name, color, created_at, updated_at
`

type UpsertTagByNameParams struct {
	Name  string `json:"name"`
	Color string `json:"color"`
}

type UpsertTagByNameRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Insert a tag by name, or return the existing live one (case-insensitive).
// ON CONFLICT targets the partial unique index on lower(name) WHERE deleted_at IS NULL.
func (q *Queries) UpsertTagByName(ctx context.Context, arg UpsertTagByNameParams) (UpsertTagByNameRow, error) {
	row := q.db.QueryRow(ctx, upsertTagByName, arg.Name, arg.Color)
	var i UpsertTagByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
