// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upcomingChanges.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertUpcomingChange = `-- name: InsertUpcomingChange :one
INSERT INTO upcoming_changes (
    token,
    type,
    user_id,
    upcoming_value,
    expired_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE($5, now() + INTERVAL '1 hour')
)
RETURNING id, token, type, upcoming_value, user_id, created_at, expired_at, revoked_at
`

type InsertUpcomingChangeParams struct {
	Token         string              `json:"token"`
	Type          UpcomingChangesType `json:"type"`
	UserID        uuid.UUID           `json:"user_id"`
	UpcomingValue *string             `json:"upcoming_value"`
	ExpiredAt     interface{}         `json:"expired_at"`
}

func (q *Queries) InsertUpcomingChange(ctx context.Context, arg InsertUpcomingChangeParams) (UpcomingChange, error) {
	row := q.db.QueryRow(ctx, insertUpcomingChange,
		arg.Token,
		arg.Type,
		arg.UserID,
		arg.UpcomingValue,
		arg.ExpiredAt,
	)
	var i UpcomingChange
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Type,
		&i.UpcomingValue,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiredAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeUpcomingChangeByID = `-- name: RevokeUpcomingChangeByID :exec
UPDATE upcoming_changes
SET revoked_at = now()
WHERE
    id = $1
    AND revoked_at IS NULL
`

func (q *Queries) RevokeUpcomingChangeByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeUpcomingChangeByID, id)
	return err
}

const selectUpcomingChangeByToken = `-- name: SelectUpcomingChangeByToken :one
SELECT id, token, type, upcoming_value, user_id, created_at, expired_at, revoked_at FROM upcoming_changes
WHERE
    token = $1
    AND revoked_at IS NULL
    AND expired_at > now()
`

func (q *Queries) SelectUpcomingChangeByToken(ctx context.Context, token string) (UpcomingChange, error) {
	row := q.db.QueryRow(ctx, selectUpcomingChangeByToken, token)
	var i UpcomingChange
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Type,
		&i.UpcomingValue,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiredAt,
		&i.RevokedAt,
	)
	return i, err
}
