// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptMember = `-- name: AcceptMember :one
UPDATE users
SET
    role = 'VIEWER',
    updated_at = now()
WHERE
    deleted_at IS NULL
    AND id = $1
    AND role = 'PENDING'
RETURNING id, name, username, email, role, created_at, updated_at
`

type AcceptMemberRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Role      UserRole  `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) AcceptMember(ctx context.Context, id uuid.UUID) (AcceptMemberRow, error) {
	row := q.db.QueryRow(ctx, acceptMember, id)
	var i AcceptMemberRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countMembers = `-- name: CountMembers :one
SELECT count(*) FROM users_view
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR role::text = $1::text
)
`

func (q *Queries) CountMembers(ctx context.Context, role *string) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertUserInvite = `-- name: InsertUserInvite :one
INSERT INTO users (name, username, email, hashed_password)
VALUES (
    $1,
    $1,
    $1,
    NULL
)
RETURNING id, name, username, email, role, created_at, updated_at
`

type InsertUserInviteRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Role      UserRole  `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Creates a passwordless PENDING user for the email-invite flow. Username/name
// default to the email until the invitee sets their own on accept.
func (q *Queries) InsertUserInvite(ctx context.Context, email string) (InsertUserInviteRow, error) {
	row := q.db.QueryRow(ctx, insertUserInvite, email)
	var i InsertUserInviteRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectMembers = `-- name: SelectMembers :many
SELECT
    uv.id, uv.name, uv.username, uv.email, uv.role, uv.created_at, uv.updated_at, uv.image,
    (u.hashed_password IS NOT NULL)::bool AS has_password,
    COALESCE((
        SELECT uc.token
        FROM upcoming_changes uc
        WHERE uc.user_id = uv.id
            AND uc.type = 'INVITE'
            AND uc.revoked_at IS NULL
            AND uc.expired_at > now()
        ORDER BY uc.created_at DESC
        LIMIT 1
    ), '')::text AS invite_token
FROM users_view uv
JOIN users u ON u.id = uv.id
WHERE (
    $1::text IS NULL
    OR $1::text = ''
    OR uv.role::text = $1::text
)
ORDER BY
    CASE WHEN $2::text = 'name_asc' THEN uv.name END ASC,
    CASE WHEN $2::text = 'name_desc' THEN uv.name END DESC,
    CASE WHEN $2::text = 'created_asc' THEN uv.created_at END ASC,
    CASE WHEN $2::text = 'created_desc' THEN uv.created_at END DESC,
    uv.created_at DESC
LIMIT $4 OFFSET $3
`

type SelectMembersParams struct {
	Role   *string `json:"role"`
	Sort   *string `json:"sort"`
	Offset int32   `json:"offset"`
	Limit  int32   `json:"limit"`
}

type SelectMembersRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Username    string    `json:"username"`
	Email       string    `json:"email"`
	Role        UserRole  `json:"role"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Image       *string   `json:"image"`
	HasPassword bool      `json:"has_password"`
	InviteToken string    `json:"invite_token"`
}

// invited_token: the active (non-revoked, non-expired) INVITE token, if any,
// so the UI can surface the accept link for pending invites.
func (q *Queries) SelectMembers(ctx context.Context, arg SelectMembersParams) ([]SelectMembersRow, error) {
	rows, err := q.db.Query(ctx, selectMembers,
		arg.Role,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectMembersRow{}
	for rows.Next() {
		var i SelectMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Image,
			&i.HasPassword,
			&i.InviteToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserById = `-- name: SelectUserById :one
SELECT id, name, username, email, role, created_at, updated_at, image FROM users_view
WHERE id = $1
LIMIT 1
`

func (q *Queries) SelectUserById(ctx context.Context, id uuid.UUID) (UsersView, error) {
	row := q.db.QueryRow(ctx, selectUserById, id)
	var i UsersView
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Image,
	)
	return i, err
}

const selectUserByIdWithPassword = `-- name: SelectUserByIdWithPassword :one
SELECT
    id,
    name,
    username,
    email,
    role,
    hashed_password,
    created_at,
    updated_at
FROM users
WHERE
    deleted_at IS NULL
    AND id = $1
LIMIT 1
`

type SelectUserByIdWithPasswordRow struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Username       string    `json:"username"`
	Email          string    `json:"email"`
	Role           UserRole  `json:"role"`
	HashedPassword *string   `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) SelectUserByIdWithPassword(ctx context.Context, id uuid.UUID) (SelectUserByIdWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, selectUserByIdWithPassword, id)
	var i SelectUserByIdWithPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPasswordAndActivate = `-- name: SetPasswordAndActivate :one
UPDATE users
SET
    hashed_password = $1,
    role = 'VIEWER',
    updated_at = now()
WHERE
    deleted_at IS NULL
    AND id = $2
RETURNING id, name, username, email, role, created_at, updated_at
`

type SetPasswordAndActivateParams struct {
	HashedPassword *string   `json:"hashed_password"`
	ID             uuid.UUID `json:"id"`
}

type SetPasswordAndActivateRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Role      UserRole  `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Invite accept: set the password and promote PENDING -> VIEWER in one step.
func (q *Queries) SetPasswordAndActivate(ctx context.Context, arg SetPasswordAndActivateParams) (SetPasswordAndActivateRow, error) {
	row := q.db.QueryRow(ctx, setPasswordAndActivate, arg.HashedPassword, arg.ID)
	var i SetPasswordAndActivateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteMember = `-- name: SoftDeleteMember :execrows
UPDATE users
SET deleted_at = now()
WHERE
    deleted_at IS NULL
    AND id = $1
`

func (q *Queries) SoftDeleteMember(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMember, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMemberStatus = `-- name: UpdateMemberStatus :one
UPDATE users
SET
    role = $1,
    updated_at = now()
WHERE
    deleted_at IS NULL
    AND id = $2
    AND role != 'PENDING'
RETURNING id, name, username, email, role, created_at, updated_at
`

type UpdateMemberStatusParams struct {
	Role UserRole  `json:"role"`
	ID   uuid.UUID `json:"id"`
}

type UpdateMemberStatusRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Role      UserRole  `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) (UpdateMemberStatusRow, error) {
	row := q.db.QueryRow(ctx, updateMemberStatus, arg.Role, arg.ID)
	var i UpdateMemberStatusRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = coalesce($1, name),
    username = coalesce($2, username),
    email = coalesce($3, email),
    hashed_password = coalesce($4, hashed_password),
    image = coalesce($5, image),
    updated_at = now()
WHERE
    deleted_at IS NULL
    AND id = $6
RETURNING id, name, username, email, role, image, created_at, updated_at
`

type UpdateUserParams struct {
	Name           *string   `json:"name"`
	Username       *string   `json:"username"`
	Email          *string   `json:"email"`
	HashedPassword *string   `json:"hashed_password"`
	Image          *string   `json:"image"`
	ID             uuid.UUID `json:"id"`
}

type UpdateUserRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Role      UserRole  `json:"role"`
	Image     *string   `json:"image"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.HashedPassword,
		arg.Image,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
