// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const selectUserById = `-- name: SelectUserById :one
SELECT id, name, username, email, role, hashed_password, created_at, updated_at, deleted_at FROM users
WHERE
    deleted_at IS null
    AND
    id = $1
LIMIT 1
`

func (q *Queries) SelectUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, selectUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = coalesce($1, name),
    username = coalesce($2, username),
    email = coalesce($3, email),
    hashed_password = coalesce($4, hashed_password),
    updated_at = now()
WHERE
    deleted_at IS null
    AND
    id = $5
RETURNING id, name, username, email, role, hashed_password, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	Name           *string   `json:"name"`
	Username       *string   `json:"username"`
	Email          *string   `json:"email"`
	HashedPassword *string   `json:"hashed_password"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.HashedPassword,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
